import test from 'node:test'
import assert from 'node:assert/strict'
import {repo} from '../scripts/validation/nonRedoxPhysicalBenchmark.js'
import {automaticBoundaries,boundaryComponents,normalizeAutomaticDefinition} from '../src/calculations/automaticBoundaries.js'
import {closedReagentExample} from '../src/data/closedReagentExample.js'
import {runAutomaticClosedCalculation,runClosedReagentCalculation,commitClosedReagentCalculation,closedReagentIds as ids} from '../src/calculations/closedReagentSetup.js'
import {chooseAxisOption,axisOptions} from '../src/calculations/axisOptions.js'
import {selectedEquilibrium} from '../src/plots/resultSelection.js'
import {deriveOutputs} from '../src/calculations/outputs.js'
import {prepareArea,configureArea} from '../src/calculations/predominanceArea.js'
const components=s=>boundaryComponents(s.chemicalSystem.selectedComponents.map(id=>repo.getComponentById(id)),repo)
function control(){const s=closedReagentExample(repo);delete s.calculationDefinition.closedReagents
s.calculationDefinition.componentConditions=s.calculationDefinition.componentConditions.filter(c=>c.componentId!==ids.peroxide).map(c=>({...c,mode:c.componentId===ids.water?'LA':'T',quantity:c.componentId===ids.water?'log-activity':'total',unit:c.componentId===ids.water?'dimensionless':'mol/kg-H2O',value:({[ids.Fe]:1e-6,[ids.proton]:.01,[ids.chloride]:.010002,[ids.water]:0})[c.componentId]}))
s.calculationDefinition.independentVariables=[{componentId:ids.peroxide,mode:'TV',quantity:'total',unit:'mol/kg-H2O',range:{min:2.5e-7,max:5e-7},points:3}];return s}
test('ordinary Calculation follows HYDRA selection without adding electron chemistry',()=>{const s=control(),b=automaticBoundaries(s.calculationDefinition,components(s),repo);assert.equal(b.redox,false);assert.equal(b.hydrogen.kind,'derived');assert.equal(b.electron.kind,'not-connected');assert.equal(b.reason,null)})
test('acetate uses derived hydrogen without unrelated database redox',()=>{const s=control();s.chemicalSystem.selectedComponents=[ids.proton,ids.water,'component:CH3COO-','component:Na%2B'];s.calculationDefinition.componentConditions=[];s.calculationDefinition.independentVariables=[];const b=automaticBoundaries(s.calculationDefinition,components(s),repo);assert.equal(b.redox,false);assert.equal(b.electron.kind,'not-connected');assert.equal(b.hydrogen.kind,'derived')})
test('axis removal clears stale pH and preserves explicit fixed conditions',()=>{const s=control(),cs=components(s),options=axisOptions(cs);let d=chooseAxisOption(s.calculationDefinition,0,options.find(o=>o.quantity==='pH'),cs);assert.equal(automaticBoundaries(d,cs,repo).hydrogen.label,'Imposed by X axis');d=normalizeAutomaticDefinition(chooseAxisOption(d,0,options.find(o=>o.component.id===ids.peroxide&&o.mode==='TV'),cs),cs);assert.equal(d.componentConditions.find(c=>c.componentId===ids.proton).mode,'T');assert.equal(automaticBoundaries(d,cs,repo).hydrogen.kind,'derived');d.componentConditions=d.componentConditions.map(c=>c.componentId===ids.proton?{...c,mode:'LA',quantity:'pH',value:7,explicit:true}:c);assert.equal(automaticBoundaries(d,cs,repo).reason,null);assert.equal(automaticBoundaries(d,cs,repo).hydrogen.label,'Imposed by fixed condition')})
test('pH/Eh area adds the potential coordinate without an electron reagent',async()=>{const s=control(),cs=components(s);s.calculationDefinition.independentVariables=[];s.calculationDefinition=configureArea(s.calculationDefinition,cs);const b=automaticBoundaries(s.calculationDefinition,cs,repo);assert.equal(b.hydrogen.label,'Imposed by X axis');assert.equal(b.electron.label,'Imposed by Y axis');assert.equal(b.reason,null);const p=await prepareArea(s,repo);assert.equal(p.ok,false);assert.match(p.reason,/basis transformation/);s.chemicalSystem.selectedComponents=[ids.proton,ids.water,ids.Fe];s.calculationDefinition.componentConditions=s.calculationDefinition.componentConditions.filter(c=>s.chemicalSystem.selectedComponents.includes(c.componentId));const supported=await prepareArea(s,repo);assert.ok(supported.ok,supported.reason)})
test('requested unbalanced Fe/peroxide inventory is explained, never silently neutralized',async()=>{const s=control();s.chemicalSystem.selectedComponents=s.chemicalSystem.selectedComponents.filter(id=>id!==ids.chloride);s.calculationDefinition.componentConditions=s.calculationDefinition.componentConditions.filter(c=>c.componentId!==ids.chloride).map(c=>({...c,value:c.componentId===ids.Fe?1:0}));s.calculationDefinition.independentVariables[0].range={min:0,max:1};s.calculationDefinition.independentVariables[0].points=51;const r=await runAutomaticClosedCalculation(s,repo);assert.equal(r.ok,false);assert.match(r.reason,/countercharge/);assert.equal(r.preparationCharge.netCharge,2)})
test('general closed composition uses exact accepted samples, reviewed overlap and unchanged output adapters',async()=>{let s=control();const r=await runAutomaticClosedCalculation(s,repo);assert.ok(r.ok,r.reason);assert.equal(r.closed.counts.accepted,3);const reviewed=closedReagentExample(repo);reviewed.calculationDefinition.closedReagents.axis={min:2.5e-7,max:5e-7,points:3};const ref=await runClosedReagentCalculation(reviewed,repo);assert.ok(ref.ok,ref.reason);for(let i=0;i<3;i++){assert.ok(Math.abs(r.closed.outcomes[i].accepted.inspection.pH-ref.closed.outcomes[i].accepted.inspection.pH)<1e-8);assert.ok(Math.abs(r.closed.outcomes[i].accepted.inspection.Eh-ref.closed.outcomes[i].accepted.inspection.Eh)<1e-8)}s=commitClosedReagentCalculation(s,r);for(const type of ['log-concentration','total-fraction','aqueous-fraction']){const out=deriveOutputs(r.system,r.sweep,{type,componentId:ids.Fe},{currentRevision:s.revision});assert.ok(out.ok,JSON.stringify(out.diagnostics))}const selected=selectedEquilibrium(s,2);assert.ok(selected.ok,selected.message);assert.equal(selected.outcome,r.sweep.outcomes[2]);assert.equal(selected.automaticClosedInspection,r.closed.outcomes[2].accepted.inspection);assert.equal(selectedEquilibrium({...s,revision:s.revision+1},2).ok,false)})
