import test from 'node:test';
import assert from 'node:assert/strict';
import {sampleInventory,separateSample,amountLabel,emptySample,partitionLabel} from '../src/beaker/sampleInventory.js';
const q={ok:true,system:{components:[{id:'cr',name:'Cr 3+'},{id:'h',name:'H+'},{id:'component:H2O',name:'H2O'}],products:[{id:'solid',name:'Cr(OH)3(s)',coefficients:[1,-3,3]}]},result:{solids:[{id:'solid',name:'Cr(OH)3(s)',amount:.01}],speciesIds:['cr','solid'],concentrations:[.001,.01]}};
test('dry mass uses source reaction stoichiometry and solvent mass',()=>{const a=sampleInventory(q,.1);assert.equal(a.solids[0].moles,.001);assert.ok(Math.abs(a.drySolidMassG-.103017)<1e-9);assert.equal(a.aqueous[0].moles,.0001);assert.equal(sampleInventory(q,.2).drySolidMassG,2*a.drySolidMassG);});
test('unknown formula never becomes a guessed mass',()=>{const b=structuredClone(q);b.system.components[0].name='Unknown';assert.equal(sampleInventory(b,.1).drySolidMassG,null);assert.equal(sampleInventory(q,null),null);});
test('separation conserves every species and solvent, without mutating the titration',()=>{const sample={accepted:true,hasAmountBasis:true,volumeMl:75,solidMoles:.001,totalSolidMoles:.001,solids:q.result.solids,visibleSolids:[{id:'solid',moles:.001}],inventory:sampleInventory(q,.1)};const original=structuredClone(sample);const {residue,filtrate}=separateSample(sample);assert.deepEqual(sample,original);assert.deepEqual(residue.inventory.solids,sample.inventory.solids);assert.deepEqual(filtrate.inventory.aqueous,sample.inventory.aqueous);assert.equal(residue.inventory.aqueous.length,0);assert.equal(filtrate.inventory.solids.length,0);assert.equal(residue.inventory.drySolidMassG+filtrate.inventory.drySolidMassG,sample.inventory.drySolidMassG);assert.equal(residue.inventory.basisKgWater+filtrate.inventory.basisKgWater,sample.inventory.basisKgWater);assert.equal(filtrate.volumeMl,75);assert.equal(residue.volumeMl,0);assert.equal(amountLabel(filtrate),'0 mg');assert.throws(()=>separateSample({accepted:false}));});
test('readout includes quantities below the drawing threshold',()=>{assert.equal(amountLabel({accepted:true,hasAmountBasis:true,totalSolidMoles:.0005,solidMoles:0}),'0.500 mmol');});

test('empty replacement clears chemistry without changing the carried snapshot',()=>{const sample={accepted:true,volumeMl:75,inventory:sampleInventory(q,.1),partitions:[{name:'Cr',solidFraction:.8,dissolvedFraction:.2}],solids:q.result.solids};const snapshot=structuredClone(sample);const empty=emptySample(sample);assert.deepEqual(sample,snapshot);assert.equal(empty.volumeMl,0);assert.equal(empty.inventory,null);assert.deepEqual(empty.solids,[]);assert.deepEqual(empty.partitions,[]);assert.equal(empty.accepted,false);assert.equal(partitionLabel(sample),'Cr: 20.0% in solution · 80.0% precipitated');});
