import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {repo} from '../scripts/validation/nonRedoxPhysicalBenchmark.js';
import {prepareSessionPoint} from '../src/solver/prepareSession.js';
import {prepareArea} from '../src/calculations/predominanceArea.js';
import {createSweepDefinition,runSweep} from '../src/calculations/sweep.js';
import {automaticBoundaries,boundaryComponents,normalizeAutomaticDefinition} from '../src/calculations/automaticBoundaries.js';
import {createPointInput} from '../src/solver/models.js';
import {deriveOutputs} from '../src/calculations/outputs.js';
const evidence=JSON.parse(fs.readFileSync('docs/spana-parity-reference.json'));
for(const f of evidence.fixtures)test('SPANA analytical parity: '+f.name,async()=>{
 const s=structuredClone(f.session),cs=boundaryComponents(s.chemicalSystem.selectedComponents.map(id=>repo.getComponentById(id)),repo),b=automaticBoundaries(s.calculationDefinition,cs,repo);assert.equal(b.reason,null);s.calculationDefinition=normalizeAutomaticDefinition(s.calculationDefinition,cs);const p=b.redox?await prepareArea(s,repo,{sweep:true}):await prepareSessionPoint(s,repo,{sweep:true});assert.ok(p.ok,JSON.stringify(p));const sd=await createSweepDefinition(p.system,p.definition??s.calculationDefinition,s.revision);assert.ok(sd.ok,JSON.stringify(sd));const result=await runSweep(p.system,sd.sweep);for(const sample of f.samples){const r=result.outcomes[sample.index];if(f.name==='fe-peroxide-analytical'&&sample.index===0){assert.equal(r.status,'failed','Zero-dose numerical gap is preserved');continue}assert.equal(r.status,'converged');assert.equal(sample.flags,0);for(const [j,id] of f.sourceSpecies.entries()){const i=p.system.speciesIds.indexOf(id);assert.ok(Math.abs(r.result.concentrations[i]-sample.C[j])<=1e-12+2e-9*Math.abs(sample.C[j]),id)}for(let j=0;j<p.system.components.length;j++)assert.ok(Math.abs(r.result.logActivities[j]-sample.logA[j])<=1e-8);}
 if(b.redox){assert.equal(p.system.redoxPolicy,'analytical-proton-fixed-electron-v1');const constraints=structuredClone(result.outcomes[0].input.constraints);constraints.find(c=>p.system.components.find(x=>x.id===c.componentId).role==='electron').kh=1;assert.equal((await createPointInput(p.system,{constraints,revision:0,unit:p.system.unit,temperatureC:25,pressureBar:1,activityModel:'ideal'})).ok,false);for(const type of ['log-concentration','calculated-pH','total-fraction','aqueous-fraction'])assert.ok(deriveOutputs(p.system,result,{type,componentId:p.componentId},{currentRevision:s.revision}).ok);}
});
test('unvalidated calculated electron balance is gated independently of physical closed chemistry',async()=>{const s=structuredClone(evidence.fixtures.find(f=>f.name==='Fe-derived-pH').session),e=repo.getComponents().find(c=>c.role==='electron');s.calculationDefinition.componentConditions=s.calculationDefinition.componentConditions.map(c=>c.componentId===e.id?{...c,mode:'T',quantity:'total',unit:'mol/kg-H2O',value:0}:c);assert.match((await prepareArea(s,repo,{sweep:true})).reason,/Calculated electron-balance/);s.calculationDefinition.closedReagents={};assert.equal(automaticBoundaries(s.calculationDefinition,boundaryComponents(s.chemicalSystem.selectedComponents.map(id=>repo.getComponentById(id)),repo),repo).reason,null)});
