import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createRepository} from '../src/thermodynamics/repository.js';import {loadWetLabIons} from '../src/calculations/wetLabIons.js';import {prepareWetLabStocks,analyticalWetLabSetup} from '../src/calculations/wetLabSetup.js';import {prepareStockPH,prepareWetLabStockEquilibria} from '../src/calculations/wetLabStockPH.js';import {createCalculationDefinition} from '../src/calculations/definition.js';import {constructEquilibrium} from '../src/thermodynamics/equilibriumConstructor.js';import {solvePoint} from '../src/solver/point.js';import {numericalValidationContract as tol} from '../src/solver/validationContract.js';import {selectedSystem,compareDose} from './helpers/wetLabCalculationParity.js';import {createWetLabExperience} from '../src/calculations/wetLabExperience.js';import {prepareWetLabScope,runTitration} from '../src/calculations/wetLabTitration.js';import {vesselSedimentHeight,liquidVisual,sedimentSegments} from '../src/beaker/scene.js';import {precipitateVisual} from '../src/beaker/visual.js';import {createWetLabAnalysis} from '../src/calculations/wetLabAnalysis.js';
const repo=createRepository(JSON.parse(fs.readFileSync('public/data/thermodynamic-default.json'))),catalog=await loadWetLabIons(repo),H='component:H%2B',W='component:H2O',C='component:CO3%202-',Ca='component:Ca%202%2B';
const setupFor=(ids,pH=5)=>({...structuredClone(analyticalWetLabSetup),sample:{preparationContract:'analytical-acid-base',initialPH:pH,volumeMl:50,contributions:ids.map((sourceId,i)=>({id:String(i),kind:'component',sourceId,concentrationMolPerL:.01}))}});
const evidence=[];
for(const [name,id,pH] of [['acetate','component:CH3COO-',5],['citrate','component:cit%203-',5],['phosphate','component:PO4%203-',5],['carbonate-acid',C,5],['carbonate-base',C,11],['calcium',Ca,7]])test('stock preparation and released inventory independently match Calculation: '+name,async()=>{
 const chemical=selectedSystem(repo,[id]),setup=setupFor([id],pH),original=prepareWetLabStocks(setup,1,catalog).sample,stock=await prepareStockPH(repo,original,pH,chemical),s=stock.stockPreparation;
 const d=createCalculationDefinition(chemical,repo);d.componentConditions=chemical.selectedComponents.map(c=>c===W?{componentId:c,mode:'LA',quantity:'log-activity',unit:'dimensionless',value:0}:c===H?{componentId:c,mode:'LA',quantity:'pH',unit:'dimensionless',value:pH}:{componentId:c,mode:'T',quantity:'total',unit:'mol/kg-H2O',value:.01});
 const prepared=await constructEquilibrium(repo,{adapter:'ordinary',session:{chemicalSystem:chemical,calculationDefinition:d,revision:1}}),direct=solvePoint(prepared.system,prepared.input);assert.equal(direct.ok,true);assert.deepEqual(s.system,prepared.system);assert.deepEqual(s.input,prepared.input);assert.deepEqual(s.result,direct);
 const hi=prepared.system.components.findIndex(c=>c.role==='proton');assert.equal(stock.moles.protonEquivalent,direct.componentTotals[hi]*.05);assert.equal(stock.chargeEquivalents,original.chargeEquivalents+stock.moles.protonEquivalent-original.moles.protonEquivalent);
 Object.assign(d.componentConditions.find(c=>c.componentId===H),{mode:'T',quantity:'total',unit:'mol/kg-H2O',value:stock.moles.protonEquivalent/.05});const round=await constructEquilibrium(repo,{adapter:'ordinary',session:{chemicalSystem:chemical,calculationDefinition:d,revision:1}}),r=solvePoint(round.system,round.input);assert.equal(r.ok,true,JSON.stringify(r.diagnostics));assert.deepEqual(r.speciesIds,direct.speciesIds);assert.deepEqual(round.system.sourceIdentity,prepared.system.sourceIdentity);
 direct.concentrations.forEach((v,i)=>assert.ok(Math.abs(v-r.concentrations[i])<=tol.comparisonAbsoluteConcentrationTolerance+tol.comparisonRelativeConcentrationTolerance*Math.abs(v)));
 direct.logActivities.forEach((v,i)=>assert.ok(Math.abs(v-r.logActivities[i])<=tol.comparisonLogActivityTolerance));assert.deepEqual(r.solids.map(s=>[s.id,s.amount,s.status]),direct.solids.map(s=>[s.id,s.amount,s.status]));r.solids.forEach((s,i)=>assert.ok(Math.abs(s.logSaturation-direct.solids[i].logSaturation)<=tol.saturatedSolidLogActivityTolerance));
 evidence.push({name,pH,protonTotal:direct.componentTotals[hi],roundtripPH:-r.logActivities[hi],stockSolids:direct.solids,sourceIdentity:prepared.system.sourceIdentity,species:direct.speciesIds.map((id,i)=>({id,name:[...prepared.system.components,...prepared.system.products][i].name,concentration:direct.concentrations[i],logActivity:direct.logActivities[i]})),residuals:r.residuals});
});
test('blank stock pH preserves exact branded inventory; heterogeneous stock refuses without suppressing solids',async()=>{
 const setup=setupFor([C,Ca],11),stocks=prepareWetLabStocks(setup,1,catalog),chemical=selectedSystem(repo,[C,Ca]);assert.equal(await prepareStockPH(repo,stocks.sample,'',chemical),stocks.sample);await assert.rejects(()=>prepareStockPH(repo,stocks.sample,11,chemical),e=>e.code==='heterogeneous-stock'&&/Transport of heterogeneous/.test(e.message));await assert.rejects(()=>prepareStockPH(repo,stocks.sample,'oops',chemical),/finite/);
});
test('Ca/carbonate independently prepared stocks transport inventories; dose parity and view/selection cause zero solves',async()=>{
 const setup=setupFor([C],5);setup.titrant={preparationContract:'analytical-acid-base',initialPH:7,volumeMl:200,contributions:[{id:'ca',kind:'component',sourceId:Ca,concentrationMolPerL:.01}]};const chemical=selectedSystem(repo,[Ca,C]);const stocks=await prepareWetLabStockEquilibria(repo,setup,1,catalog,chemical);assert.equal(stocks.sample.stockPreparation.chemicalSystem.selectedComponents.includes(Ca),false);assert.equal(stocks.titrant.stockPreparation.chemicalSystem.selectedComponents.includes(C),false);
 let solves=0;const engine=await createWetLabExperience(repo,{chemicalSystem:chemical,setup,onSolve:()=>solves++}),analysis=createWetLabAnalysis(engine),snap=engine.snapshot();assert.equal(snap.solveCounts.stock,2);assert.equal(solves,snap.equilibriumSolveCount);const doseEvidence=[];
 for(const volume of [0,50,100,200]){const p=snap.points.find(p=>p.x===volume);doseEvidence.push(await compareDose(repo,chemical,p.state));engine.select(p);const count=solves;for(let repeat=0;repeat<3;repeat++){for(const type of ['titration','log-concentration','total-fraction','aqueous-fraction']){analysis.view(type,C);assert.equal(analysis.inspect(p),p.state)}engine.preview(p);engine.clearPreview();await engine.setVolume(volume);assert.equal(engine.snapshot().selected,p.state)}assert.equal(solves,count);assert.equal(p.state.analyticalMoles.protonEquivalent,stocks.sample.moles.protonEquivalent+stocks.titrant.moles.protonEquivalent*volume/200)}
 assert.equal(snap.points[0].state.status,'unavailable');assert.ok(snap.points.slice(1).every(p=>p.state.status==='accepted-v0'));fs.writeFileSync('.local/stock-ph-workspace/science.json',JSON.stringify({stocks:evidence,doses:doseEvidence,timings:snap.timings,solveCounts:snap.solveCounts,zeroSolveSwitching:true},null,2));engine.dispose();assert.throws(()=>engine.select(snap.points[1]),/current/);
});

test('stock-pH titration doses preserve Calculation parity across acid/base families',async()=>{
 const rows=[];for(const ids of [['component:CH3COO-'],['component:cit%203-'],['component:PO4%203-'],[C],['component:CH3COO-','component:HCOO-']]){
  const setup=setupFor(ids,5);setup.titrant.initialPH=1;const chemical=selectedSystem(repo,ids),stocks=await prepareWetLabStockEquilibria(repo,setup,1,catalog,chemical),context=await prepareWetLabScope(repo,stocks,chemical,1),series=await runTitration(context,{analyteStock:stocks.sample,analyteVolumeMl:50,titrantStock:stocks.titrant,additionVolumesMl:[0,25,50,100],revision:1});
  for(const state of series.states){assert.equal(state.status,'accepted-v0');rows.push({ids,...await compareDose(repo,chemical,state)})}
 }fs.writeFileSync('.local/stock-ph-workspace/acid-base-doses.json',JSON.stringify(rows,null,2));
});
test('homogeneous carbonate pH 11 and calcium pH 7 produce accepted precipitation after mixing',async()=>{
 const setup=setupFor([C],11);setup.titrant={preparationContract:'analytical-acid-base',initialPH:7,volumeMl:200,contributions:[{id:'ca',kind:'component',sourceId:Ca,concentrationMolPerL:.01}]};const chemical=selectedSystem(repo,[Ca,C]),stocks=await prepareWetLabStockEquilibria(repo,setup,1,catalog,chemical),context=await prepareWetLabScope(repo,stocks,chemical,1),series=await runTitration(context,{analyteStock:stocks.sample,analyteVolumeMl:50,titrantStock:stocks.titrant,additionVolumesMl:[0,2,25,50,100,200],revision:1}),rows=[];
 assert.equal(series.states[0].status,'unavailable');for(const state of series.states.slice(1)){assert.equal(state.status,'accepted-v0');rows.push(await compareDose(repo,chemical,state));const q=state.equilibrium.inspection;assert.ok(q.solids.some(s=>s.name==='CaCO3(cr)'&&s.amount>0));assert.ok(sedimentSegments(q).length>0);assert.ok(vesselSedimentHeight(q,liquidVisual(state.totalVolumeMl,250))>0)}fs.writeFileSync('.local/stock-ph-workspace/precipitation.json',JSON.stringify(rows,null,2));
});
test('shared sediment height stays monotonic and below a quarter of fixed or volume-linked liquid depth',()=>{
 for(const liquid of [liquidVisual(),liquidVisual(50,250),liquidVisual(100,250),liquidVisual(250,250)]){let previous=0;for(const amount of [0,1e-30,1e-12,2e-12,1e-6,.001,.01,.1,1,100]){const solids=[{id:'one',amount}],state={ok:true,solids,visual:precipitateVisual(solids)},before=JSON.stringify(state),height=vesselSedimentHeight(state,liquid);assert.ok(height>=previous&&height<=(315-liquid.top)*.24);previous=height;assert.equal(JSON.stringify(state),before)}}assert.equal(vesselSedimentHeight({ok:false},liquidVisual()),0);
 const state={ok:true,solids:[{id:'a',amount:.001},{id:'b',amount:.003}]};state.visual=precipitateVisual(state.solids);const segments=sedimentSegments(state);assert.equal(segments.length,2);assert.equal(segments[1].width/segments[0].width,3);
});
