import fs from 'node:fs'
import {registerHooks} from 'node:module'
let captured=[]
globalThis.captureHydraJacobian=x=>captured.push(x)
registerHooks({load(url,context,next){const r=next(url,context);if(url.endsWith('/src/solver/point.js'))return {...r,source:String(r.source).replace('const linear = solveLinear(jacobian, residual.map(r => -r))','globalThis.captureHydraJacobian({iteration,jacobian,logA:state.logA}); const linear = solveLinear(jacobian, residual.map(r => -r))')};return r}})
const {repo}=await import('./nonRedoxPhysicalBenchmark.js'),{request}=await import('./exactConservationRun.js'),{compileEquilibriumNetwork,solveEquilibriumNetwork}=await import('../../src/thermodynamics/equilibriumNetwork.js'),{prepareClosedRedox,solveClosedRedox}=await import('../../src/solver/closedRedox.js'),{phaseRank}=await import('../../src/solver/assemblages.js')
const compiled=await compileEquilibriumNetwork(repo,request({'component:Na%2B':.01,'component:NO3-':.01})),original=solveEquilibriumNetwork(compiled),base=compiled.preparedSystemInput.prepared,n=base.network
const variants=[{id:n.basisIds[0],name:'original'},...n.sourceSpecies.filter(s=>!n.basisIds.includes(s.id)&&s.role==='ordinary'&&n.algebra.componentExpressions[s.id].coefficients[0]!==0).sort((a,b)=>a.id.localeCompare(b.id))]
const outputs=[]
for(const variant of variants){captured=[];const q={mode:'closed-redox',conservationMethod:'source-exact-v1',sourceFingerprint:n.sourceFingerprint,temperatureC:25,pressureBar:1,activityModel:'ideal',unit:'mol/kg-H2O',revision:0,species:n.sourceSpecies,reactions:[...n.halves,...n.ordinaryReactions],basisIds:[variant.id,...n.basisIds.slice(1)],electronId:n.electronId,solvent:{kind:'fixed-water-activity',speciesId:n.water.id,logActivity:0},preparation:base.preparation};const p=await prepareClosedRedox(q),r=p.ok?solveClosedRedox(p):p;outputs.push({basisId:variant.id,name:variant.name,prepared:p.ok,acceptedClosed:r.ok,initialRank:captured[0]?phaseRank(captured[0].jacobian):null,first:captured[0],attempts:r.result?.attempts,diagnostics:r.diagnostics,pH:r.inspection?.pH,pe:r.inspection?.pe,inventoryChecks:r.inspection?.inventories});}
fs.writeFileSync('docs/hydra-nitrate-basis-audit.json',JSON.stringify({original,network:{species:n.sourceSpecies.length,reactions:n.halves.length+n.ordinaryReactions.length,rank:n.algebra.rank,conservation:n.sourceConservation.dimension},policy:'Deterministic exhaustive one-column basis exchanges; unchanged default initialization and solver. Research diagnostics only; no production fallback.',outputs},null,2));console.table(outputs.map(({name,prepared,acceptedClosed,initialRank,pH,pe})=>({name,prepared,acceptedClosed,initialRank,pH,pe})))
