import fs from 'node:fs';import {createRepository} from '../../src/thermodynamics/repository.js';import {discoverGeneralClosed,prepareGeneralClosed,solveGeneralClosed} from '../../src/thermodynamics/generalClosedReagents.js';import {prepareClosedReagents,solveClosedReagents} from '../../src/thermodynamics/closedReagents.js';import {fePeroxideScope} from '../../src/thermodynamics/scopes/fePeroxide.js';import {identity} from '../../src/solver/models.js';
const repo=createRepository(JSON.parse(fs.readFileSync('public/data/thermodynamic-default.json'))),P='component:H2O2',W='component:H2O',F='component:Fe%202%2B',H='component:H%2B',Cl='component:Cl-';
const request=amounts=>({amounts,description:'General closure evidence',revision:0,temperatureC:25,pressureBar:1,activityModel:'ideal',unit:'mol/kg-H2O'});
const audit=await discoverGeneralClosed(repo,[P,W]),result=solveGeneralClosed(await prepareGeneralClosed(repo,request({[P]:1e-6}),audit)),ref=JSON.parse(fs.readFileSync('docs/general-closed-independent.json'));
const feAudit=await discoverGeneralClosed(repo,[F,P,H,Cl,W],{reviewedScope:true}),feRequest=request({[F]:1e-6,[P]:2.5e-7,[H]:.01,[Cl]:.010002}),old=solveClosedReagents(await prepareClosedReagents(repo,feRequest,fePeroxideScope)),current=solveGeneralClosed(await prepareGeneralClosed(repo,feRequest,feAudit));
const high=solveGeneralClosed(await prepareGeneralClosed(repo,request({[P]:.01}),audit)),unrestricted=await discoverGeneralClosed(repo,[F,P,H,Cl,W]);
const summarize=a=>({status:a.status,canCalculate:a.canCalculate,reasons:a.reasons,rows:a.included,excluded:a.excluded,redoxFamilies:a.redoxFamilies,ordinary:a.ordinary,componentRoles:a.componentRoles,basis:a.scope?.bases,conservation:a.conservation,conservationPhysicalIds:a.conservationPhysicalIds,conservationBasisIds:a.conservationBasisIds,cycleChecks:a.cycleChecks});
fs.writeFileSync('docs/general-closed-validation.json',JSON.stringify({version:audit.version,control:{audit:summarize(audit),independent:ref,inspection:result.accepted.inspection,phaseDiagnostics:result.phaseDiagnostics,gasFugacitySum:result.gasFugacitySum},Fe:{audit:summarize(feAudit),oldAcceptedHash:await identity(old),generalAcceptedHash:await identity(current.accepted),exact:JSON.stringify(old)===JSON.stringify(current.accepted)},refusals:{highPeroxide:{ok:high.ok,status:high.status,reasons:high.diagnostics,phaseDiagnostics:high.phaseDiagnostics,gasFugacitySum:high.gasFugacitySum},unrestrictedFe:summarize(unrestricted)}},null,2));
console.log({control:result.status,pH:result.accepted.inspection.pH,Eh:result.accepted.inspection.Eh,FeExact:JSON.stringify(old)===JSON.stringify(current.accepted),highDose:high.status});
