import {useContext,useMemo} from 'react'
import {ResultSelectionContext} from './ResultSelectionContext.js'
import {exportPourbaix} from '../calculations/boundedPourbaix.js'
import {publicFeSample} from '../calculations/publicFePourbaix.js'
import {fePourbaixSvg,feRegionStyles,feRepresentatives,feSampleIndex,feKeyboardIndex} from '../plots/fePourbaixView.js'
import {chemicalLabel} from '../chemistry/format.js'
import {FePhaseDisclosure} from './FePourbaixSetup.jsx'
import PlotExport from './PlotExport.jsx'
import './FePourbaix.css'
const number=n=>Number.isFinite(n)?Number(n.toPrecision(7)).toString():'Unavailable'
const carrierLabel=c=>c.id==='spana:2ac52a30213c9288:138672'?'FeO₄²⁻':chemicalLabel(c.name)
const download=(text,type,name)=>{const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function FePourbaixWorkspace({session}){
 const shared=useContext(ResultSelectionContext),r=session.lastPlot.publicFe,index=shared.index,c=publicFeSample(r,index,session.revision)
 const svg=useMemo(()=>fePourbaixSvg(r,index,session.revision),[r,index,session.revision]),representatives=useMemo(()=>feRepresentatives(r),[r])
 const sample=e=>{const b=e.currentTarget.getBoundingClientRect();return feSampleIndex(((e.clientX-b.left)/b.width*900-68)/800*14,(596-(e.clientY-b.top)/b.height*660)/558*2.2-1)}
 return <section className="fe-workspace" data-diagram="pourbaix"><h2>Fe oxidation-state predominance</h2><p className="fe-contract">Total Fe = 0.001 mol/kg H₂O · 25 °C · 1 bar declared · Ideal<br/>Validated bounded scope · 57 × 45 calculated points</p>
 {!c?<p role="alert">This Fe map is unavailable or belongs to old conditions. Recalculate the validated setup; no current regions are assigned.</p>:<>
 <div className="fe-legend" aria-label="Oxidation-state regions">{Object.entries(feRegionStyles).map(([state,s])=><button key={state} onClick={()=>shared.pin(representatives[state].index)}><span style={{background:s.color}}/>{s.label}</button>)}</div>
 <div className="plot-toolbar"><PlotExport><button onClick={()=>download(svg,'image/svg+xml','fe-pourbaix-v1.svg')}>Export SVG</button><button onClick={()=>download(JSON.stringify({...exportPourbaix(r.pourbaix,session.revision),support:r.support},null,2),'application/json','fe-pourbaix-v1.json')}>Export numerical JSON</button></PlotExport></div>
 <div className="fe-map" tabIndex={0} role="group" aria-label="Interactive Fe Pourbaix map" aria-describedby="fe-map-help" onPointerMove={e=>{if(e.pointerType!=='touch')shared.preview(sample(e))}} onPointerLeave={()=>shared.preview(null)} onClick={e=>shared.pin(sample(e))} onKeyDown={e=>{const next=feKeyboardIndex(shared.pinned,e.key);if(next!==null){e.preventDefault();shared.pin(next)}}} dangerouslySetInnerHTML={{__html:svg}}/>
 <p id="fe-map-help" className="fe-note">Click or hover to inspect a calculated point. Keyboard: arrow keys select adjacent samples; Home/End select the first/last sample. Boundaries reflect calculated grid resolution (ΔpH 0.25 · ΔEh 0.05 V).</p>
 <p className="fe-note">Region colors identify oxidation states, not physical chemical appearance. Hatching preserves the calculated regions above O₂ and below H₂; Fe(VI) remains a valid fixed-Eh result outside the conventional water window.</p>
 <section className="fe-inspection" aria-label="Fe point inspection" data-input-id={c.inputId} data-sample-index={index}><h3>{feRegionStyles[c.predominant]?.label??'Tie / transition'} <small>· {shared.hover===null?'Selected':'Hovered'} sample {index}</small></h3><label>Map sample<input type="number" min="0" max="2564" aria-label="Fe map sample" value={index} onChange={e=>shared.pin(Number(e.target.value))}/></label><p>pH {number(c.pH)} · Eh {number(c.Eh)} V vs SHE · pe {number(c.pe)}<br/>Total Fe: {number(c.totalFe)} mol/kg H₂O</p><table><caption>Oxidation-state inventory · denominator is total Fe</caption><tbody>{Object.entries(feRegionStyles).map(([state,s])=><tr key={state}><th scope="row">{s.label}</th><td>{number(100*(c.fractions.find(f=>f.oxidationState===Number(state))?.fraction??0))}% of total Fe</td></tr>)}</tbody></table><p>Predominant: {feRegionStyles[c.predominant]?.label??'Tie / transition'} · Majority (&gt;50%): {c.majority?'yes':'no'} · Tie: {c.status==='tie'?'yes':'no'}</p><p><strong>Dominant thermodynamic carrier{c.dominantThermodynamicCarriers.length===1?'':'s'}:</strong> {c.dominantThermodynamicCarriers.map(p=>`${carrierLabel(p)} (${p.phase})`).join(', ')||'No single carrier assigned during a tie'}</p><p>Dissolved Fe: {number(c.dissolvedInventory)} mol/kg H₂O<br/>Accepted solids: {c.acceptedSolids.map(s=>`${chemicalLabel(s.name)}: ${number(s.amount)} mol/kg H₂O`).join('; ')||'none'}<br/>Water context: {c.waterWindow.replaceAll('-',' ').replace('O2','O₂').replace('H2','H₂')}<br/>Solver: {c.solverStatus} · Unresolved Fe inventory: {number(c.unresolvedInventory)} mol/kg H₂O</p><details><summary>Exact fractions, carriers and provenance</summary><pre>{JSON.stringify(c,null,2)}</pre></details></section>
 </>}
 <FePhaseDisclosure/><details><summary>Water reference assumptions and scientific scope</summary><p>H₂ and O₂ are conventional reference overlays at 25 °C, SHE-based Eh, unit normalized gas fugacity/activity and a(H₂O)=1. No analytical gas inventory is solved.</p><p>Equilibrium oxidation-state predominance does not predict corrosion rate, reaction kinetics, nucleation, passivation rate, metastable persistence or actual precipitate appearance.</p><p>Only this Fe total and phase scope are validated. Cu, Mn, arbitrary Fe totals, other temperatures and nonideal models remain unsupported.</p></details></section>
}
