import {displayNumber} from '../plots/formatNumber.js'
import MassInput from './MassInput.jsx'
import { logLandmarks } from '../plots/logLandmarks.js'
import { chemicalLabel } from '../chemistry/format.js'
import { createCondition } from '../calculations/definition.js'
import { parameterRange,positionToParameter,numericParameter } from '../plots/parameterScale.js'
import AmountUnitSelect from './AmountUnitSelect.jsx'
export default function FixedCondition({component:c,condition,onChange,compact=false}) {
  const total=condition.mode==='T', scale=parameterRange(condition)
  const options=c.role==='proton'?[['pH','pH'],['log-activity','Log activity'],['total','Signed proton balance']]:c.role==='electron'?[['Eh','Eh (V vs SHE)'],['pe','pe'],['log-activity','Log activity']]:[['total','Total concentration'],['log-activity','Log activity']]
  if(compact)return <div className="live-condition compact-total"><strong>{chemicalLabel(c.name)} {total?(c.role==='proton'?'balance':'total'):condition.quantity}</strong><label className="compact-value"><span className="sr-only">{chemicalLabel(c.name)} value</span><input className="field-editable" type="number" step="any" value={condition.value??''} placeholder="Enter a value" onChange={e=>onChange({...condition,massInput:undefined,value:numericParameter(e.target.value)})}/></label>{total?<AmountUnitSelect compact label={chemicalLabel(c.name)+' unit'} unit={condition.unit}/>:<small>{condition.quantity==='Eh'?'V vs SHE':'Dimensionless'}</small>}<details><summary>Options</summary><label>Control<select className="field-editable" value={total?'total':condition.quantity} onChange={e=>onChange(createCondition(c,e.target.value==='total'?'T':'LA',e.target.value))}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{total&&c.role==='basis-choice'&&<MassInput component={c} condition={condition} onChange={onChange}/>}</details></div>
  return <fieldset className="live-condition"><legend>{chemicalLabel(c.name)} <small>{total?'component total':'fixed activity'}</small></legend>
    <label>{chemicalLabel(c.name)} control<select className="field-editable" value={total?'total':condition.quantity} onChange={e=>onChange(createCondition(c,e.target.value==='total'?'T':'LA',e.target.value))}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
    <label>{chemicalLabel(c.name)} value<input className="field-editable" type="number" step="any" value={condition.value??''} placeholder="Enter a value" onChange={e=>onChange({...condition,massInput:undefined,value:numericParameter(e.target.value)})}/></label>
    {total?<AmountUnitSelect label={`${chemicalLabel(c.name)} unit`} unit={condition.unit}/>:<small>{condition.quantity==='Eh'?'V relative to SHE':condition.quantity==='log-activity'?'log₁₀ activity':'Dimensionless'}</small>}
    {!compact&&Number.isFinite(condition.value)&&(total?condition.value>0:true)&&<label className="live-slider"><span>{total?'Adjust total (log scale)':'Adjust activity'}</span><input aria-label={`Adjust ${chemicalLabel(c.name)}`} type="range" aria-orientation="vertical" aria-valuetext={`${displayNumber(condition.value,condition.quantity)} ${condition.unit}`} min={scale.min} max={scale.max} step={condition.quantity==='Eh'?0.005:0.05} value={scale.position} onChange={e=>onChange({...condition,massInput:undefined,value:positionToParameter(Number(e.target.value),total)})}/>{total && <div className="bar-landmarks" aria-hidden="true">{logLandmarks(scale.min, scale.max, scale.position, 220).map(t => <span key={t.value} className={t.major ? 'major' : 'minor'} style={{bottom:`${100*(t.value-scale.min)/(scale.max-scale.min)}%`}}>{t.major?t.value:'·'}</span>)}</div>}<small className="bar-caption" title="Convenience range only; type any supported value above.">{total?`log10 C = ${displayNumber(scale.position,'log')} · mol/kg H₂O`:'Drag or use arrow keys'}</small></label>}
    {total&&c.role==='basis-choice'&&<MassInput component={c} condition={condition} onChange={onChange}/>}
  </fieldset>
}
