import {useState} from 'react'
import {calculateFluoride,fluorideCSV} from '../ise/fluoride.js'
const parse=value=>value.trim()===''?NaN:Number(value.replace(',','.'))
export default function ISECalculation({onUseReadings,onInvalidate}){
 const [fields,setFields]=useState({sampleId:'',e0:'',e1:'',e2:'',mass:'',uranium:'87.5',add1:'0.5',add2:'1.0'}),[saved,setSaved]=useState(null),[error,setError]=useState('')
 function change(key,value){onInvalidate();setFields(previous=>({...previous,[key]:value}));setSaved(null);setError('')}
 function calculate(event){event.preventDefault();try{const result=calculateFluoride([fields.e0,fields.e1,fields.e2].map(parse),parse(fields.mass),parse(fields.uranium),[parse(fields.add1),parse(fields.add2)]);const record={result,sampleId:fields.sampleId,timestamp:new Date().toISOString()};setSaved(record);onUseReadings(record);setError('')}catch(e){setSaved(null);setError(e.message)}}
 function download(){const blob=new Blob([fluorideCSV(saved.result,saved.sampleId,saved.timestamp)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fluoride-${saved.sampleId.replace(/[^a-zA-Z0-9_.-]/g,'_')||'sample'}.csv`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const result=saved?.result
 return <section className="ise-calculation" aria-label="Fluoride concentration calculation"><h3>Sample &amp; readings</h3><p>Enter all three measured potentials and the sample weight before starting the animation.</p><div className="ise-calculation-grid"><form onSubmit={calculate}><div className="ise-inputs">{[['sampleId','Sample ID'],['e0','E0 · before addition (mV)'],['e1','E1 · after first addition (mV)'],['e2','E2 · after second addition (mV)'],['mass','Sample mass (g)']].map(([key,label])=><label key={key}>{label}<input value={fields[key]} inputMode={key==='sampleId'?'text':'decimal'} onChange={event=>change(key,event.target.value)}/></label>)}</div><details open className="ise-method-settings"><summary>Method defaults · uranium content and addition volumes</summary><div className="ise-inputs">{[['uranium','Assumed uranium content (%)'],['add1','First standard addition (mL)'],['add2','Second standard addition (mL, additional)']].map(([key,label])=><label key={key}>{label}<input value={fields[key]} inputMode="decimal" onChange={event=>change(key,event.target.value)}/></label>)}</div><small>1000 mg/L F⁻ standard · initial solution 58 mL. The second addition is delivered in two equal pulses.</small></details><div className="ise-calculation-actions"><button type="submit" className="ise-primary">Prepare animation</button><button type="button" onClick={()=>{onInvalidate();setSaved(null);setError('');setFields({...fields,e0:'56.5',e1:'27.5',e2:'6.6',mass:'2.000'})}}>Load example readings</button></div>{error&&<p role="alert">{error}</p>}<small>Uses your supplied method: equate the two dilution-corrected slopes. Uranium content defaults to 87.5%. The slope acceptance interval is −60.5 to −54.0 mV/decade.</small></form><div aria-live="polite">{result?<><dl className="ise-assay-results"><div><dt>F⁻ in initial 58 mL solution</dt><dd>{result.initialMgL.toFixed(1)} mg/L</dd></div><div><dt>F⁻ in original 8 mL solution</dt><dd>{result.originalMgL.toFixed(1)} mg/L</dd></div><div><dt>F⁻ per sample mass</dt><dd>{result.sampleUgG.toFixed(1)} µg/g sample</dd></div><div><dt>F⁻ per uranium mass</dt><dd>{result.uraniumUgG.toFixed(1)} µg/g U</dd></div></dl><p>S01: {result.slopes[0].toFixed(1)} · S12: {result.slopes[1].toFixed(1)} · Mean: {result.meanSlope.toFixed(1)} mV/decade</p><div className="ise-slope-result"><strong>Electrode slope: {result.meanSlope.toFixed(1)} mV/decade</strong><span>{result.slopePass?'Within method range':'Outside method range'} · −60.5 to −54.0 mV/decade</span></div><div className="ise-calculation-actions"><button onClick={download}>Save CSV</button></div><ResponsePlot result={result}/><small>The fitted line checks consistency within this standard-addition model; it is not an independent calibration. Particle counts remain illustrative.</small></>:<p>Enter the three measured potentials and sample mass, then calculate. Use Load example readings to try the supplied example.</p>}</div></div></section>
}
function ResponsePlot({result}){
 const xs=result.concentrations.map(Math.log10),lo=Math.min(...xs),hi=Math.max(...xs),emin=Math.min(...result.readings)-5,emax=Math.max(...result.readings)+5
 const x=value=>70+(value-lo)/(hi-lo)*450,y=value=>235-(value-emin)/(emax-emin)*190
 return <svg className="ise-response-plot" viewBox="0 0 600 290" role="img" aria-label="Measured electrode potential versus log fluoride concentration, with fitted response line"><title>Response slope {result.regressionSlope.toFixed(1)} mV per decade</title><path d="M70 35V235H540" fill="none" stroke="currentColor"/>{[0,.5,1].map(t=>{const e=emin+t*(emax-emin),v=lo+t*(hi-lo);return <g key={t}><text x="58" y={y(e)+4} textAnchor="end">{e.toFixed(0)}</text><text x={x(v)} y="255" textAnchor="middle">{v.toFixed(2)}</text></g>})}<line x1={x(lo)} y1={y(result.regressionSlope*lo+result.regressionIntercept)} x2={x(hi)} y2={y(result.regressionSlope*hi+result.regressionIntercept)} stroke="#adcfc6" strokeWidth="2"/>{xs.map((v,i)=><g key={i}><circle cx={x(v)} cy={y(result.readings[i])} r="5" fill="#f52236"/><text x={x(v)+(i===2?-8:8)} y={y(result.readings[i])-10} textAnchor={i===2?'end':'start'}>{['Initial',`+${result.additionVolumesMl[0]} mL`,`+${result.additionVolumesMl[0]+result.additionVolumesMl[1]} mL total`][i]}</text></g>)}<text x="24" y="145" textAnchor="middle" transform="rotate(-90 24 145)">E (mV)</text><text x="300" y="282" textAnchor="middle">log₁₀(F⁻ / mg L⁻¹)</text></svg>
}
