import {useState} from 'react'
import {loadMnSnapshot,classifySnapshot,mnDiagnosticExport} from '../analysis/mnDiagnostic.js'
import {diagnosticSvg,diagnosticModes} from '../plots/mnDiagnostic.js'
import {displayNumber as f} from '../plots/formatNumber.js'
import JsonDetails from './JsonDetails.jsx'
import ExpandedPlot from './ExpandedPlot.jsx'
import './MnDiagnostic.css'
import {regionSvg} from '../plots/mnRegions.js'
import {mnRegionSha256} from '../data/mnRegionIdentity.js'
import {mnTopologySha256} from '../data/mnTopologyIdentity.js'
import {topologySvg} from '../plots/mnTopology.js'
const download=(name,type,text)=>{const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function MnDiagnostic(){
 const [snapshot,setSnapshot]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false),[current,setCurrent]=useState(true),[mode,setMode]=useState('assemblage'),[water,setWater]=useState(false),[selected,setSelected]=useState(97)
 const load=async()=>{setBusy(true);setError(null);try{const responses=await Promise.all(['mn-retry-validation.json','mn-diagnostic-inventory.json'].map(file=>fetch(`${import.meta.env.BASE_URL}docs/${file}`)));if(responses.some(r=>!r.ok))throw Error('Local validation evidence unavailable. This diagnostic requires the development server.');const [e,i]=await Promise.all(responses.map(r=>r.text()));setSnapshot(await loadMnSnapshot(e,i));setCurrent(true)}catch(e){setError(e.message);setCurrent(false)}finally{setBusy(false)}}
 const [regions,setRegions]=useState(null),[view,setView]=useState('sampled')
 const [topology,setTopology]=useState(null),[topologySelection,setTopologySelection]=useState(null)
 const loadTopology=async()=>{try{const r=await fetch(`${import.meta.env.BASE_URL}docs/mn-topology-view.json`);if(!r.ok)throw Error('Topology audit unavailable');const text=await r.text(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(n=>n.toString(16).padStart(2,'0')).join('');if(hash!==mnTopologySha256)throw Error('Topology audit differs from pinned evidence');const v=JSON.parse(text);if(v.identity.evidenceSha256!==snapshot.identity.evidenceSha256)throw Error('Topology snapshot mismatch');setTopology(v);setView('boundaries');setError(null)}catch(e){setError(e.message);setTopology(null);setView('sampled')}}
 const loadRegions=async()=>{try{const r=await fetch(`${import.meta.env.BASE_URL}docs/mn-region-enclosures.json`);if(!r.ok)throw Error('Region audit unavailable');const text=await r.text();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(n=>n.toString(16).padStart(2,'0')).join('');if(hash!==mnRegionSha256)throw Error('Region audit differs from the pinned validated artifact');const v=JSON.parse(text);if(v.identity.evidenceSha256!==snapshot.identity.evidenceSha256)throw Error('Region evidence mismatch');setRegions(v);setView('combined')}catch(e){setError(e.message);setView('sampled')}}
 const points=snapshot?classifySnapshot(snapshot,current):[],point=points[selected],raw=snapshot?.evidence.grid.outcomes[selected],c=point?.classification
 const svg=snapshot?(regions&&view!=='sampled'&&current?(topology?topologySvg(snapshot,regions,topology,points,view==='combined',view==='boundaries',water,selected):regionSvg(snapshot,regions,points,view==='combined',water,selected)):diagnosticSvg(snapshot,points,mode,water,selected)):''
 const choose=e=>{const target=e.target.closest('[data-segment],[data-junction]');if(target&&(e.type==='click'||e.key==='Enter'||e.key===' ')){e.preventDefault();setTopologySelection(target.dataset.segment?topology.segments.find(s=>s.id===target.dataset.segment):topology.junctions.find(j=>j.id===target.dataset.junction));return}if(regions&&view!=='sampled'&&e.type==='click'&&!e.target.closest('[data-sample]')){const svg=e.target.closest('svg');if(svg){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform(svg.getScreenCTM().inverse()),h=(v.x-75)/43,eh=(555-v.y)/136-1.5;if(h>=0&&h<=14&&eh>=-1.5&&eh<=1.5){setSelected(points.reduce((a,b)=>((b.pH-h)/14)**2+((b.Eh-eh)/3)**2<((a.pH-h)/14)**2+((a.Eh-eh)/3)**2?b:a).index);return}}}const node=e.target.closest('[data-sample]');if(node&&(e.type==='click'||e.key==='Enter'||e.key===' ')){e.preventDefault();setSelected(Number(node.dataset.sample))}}
 return <section className="mn-diagnostic"><h2>Internal diagnostic Mn Pourbaix</h2><p>Explicit opt-in · saved validated Mn example, independent of your current editable system. No chemistry is recalculated. Public general Pourbaix remains unavailable.</p><button disabled={busy} onClick={load}>{busy?'Verifying saved evidence…':snapshot?'Revalidate saved snapshot':'Load validated 195-point Mn snapshot'}</button>{error&&<p role="alert">{error} Retained results, if any, keep their original conditions and are marked stale.</p>}
 {snapshot&&<><button onClick={loadRegions}>Load partial refined-region audit</button>{regions&&<><button onClick={loadTopology}>Load validated topology audit</button>{topology&&<><p>{topology.regionChange}</p><a href={`${import.meta.env.BASE_URL}docs/mn-topology-validation.json.gz`} download>Export full segment and junction evidence (gzip JSON)</a></>}<label>Comparison view<select value={view} onChange={e=>setView(e.target.value)}><option value="sampled">Diagnostic sampled map</option><option value="regions">Certified interiors (partial)</option>{topology&&<option value="boundaries">Certified interiors + boundaries</option>}<option value="combined">Certified interiors + sampled points</option></select></label><p>{regions.warning}</p><a href={`${import.meta.env.BASE_URL}docs/mn-boundary-validation.json`} download>Export complete boundary audit JSON</a></>}<div className="mn-toolbar"><label>Map interpretation<select disabled={view!=='sampled'} value={mode} onChange={e=>setMode(e.target.value)}>{diagnosticModes.map(m=><option key={m} value={m}>{m==='assemblage'?'Accepted phase / assemblage':m==='species'?'Predominant dissolved Mn species':'Predominant dissolved Mn oxidation state'}</option>)}</select></label><label><input type="checkbox" checked={water} onChange={e=>setWater(e.target.checked)}/>Analytical H₂/O₂ reference overlays</label><button onClick={()=>download('mn-diagnostic.json','application/json',mnDiagnosticExport(snapshot,mode,water,current))}>Export exact JSON</button><button onClick={()=>download('mn-diagnostic.svg','image/svg+xml',svg)}>Export SVG</button></div>
 {!current&&<p role="alert">STALE — snapshot could not be revalidated; no current classifications are assigned.</p>}
 <ExpandedPlot available><div className="mn-layout"><div onClick={choose} onKeyDown={choose} dangerouslySetInnerHTML={{__html:svg}}/><aside aria-label="Mn point inspection">{topologySelection&&view!=='sampled'&&<section aria-label="Selected topology evidence"><h3>{topologySelection.id}</h3><p>{topologySelection.states.map(s=>s.ids.map(id=>snapshot.inventory.species.find(p=>p.id===id)?.name??id).join(' + ')).join(' ↔ ')}</p><p>{topologySelection.status}: {topologySelection.reason}</p><p>Trace samples are accepted states on either side. A pure-solid equality does not assign a unique phase-amount split on the boundary.</p><JsonDetails title="Segment/junction states, supporting evaluations, uncertainty and residuals" value={topologySelection}/><button onClick={()=>setTopologySelection(null)}>Close topology inspection</button></section>}<h3>Inspect original stored sample {selected}</h3>{view!=='sampled'&&<p>Nearest stored sample, not a new equilibrium at the clicked coordinate. Read the exact coordinates below.</p>}<label>Sample index<input type="number" min="0" max="194" value={selected} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=0&&n<195)setSelected(n)}}/></label><p>pH {f(point.pH,'pH')} · Eh {f(point.Eh,'Eh')} V vs SHE · pe {f(point.pe)} · 25 °C</p><p>Mn analytical total: 0.001 mol/kg-H₂O</p><p>{c.reason}</p>{c.status==='accepted'&&<><p>Dissolved Mn: {f(c.dissolved,'concentration')} mol/kg-H₂O</p><h4>Accepted active solids</h4>{c.activeSolids.length?c.activeSolids.map(s=><p key={s.id}>{s.name}: {f(s.amount,'amount')} mol/kg · log saturation {f(s.logSaturation)}</p>):<p>None. Near-zero saturation alone does not make a phase active.</p>}<h4>Aqueous contributions</h4><div className="mn-table"><table><thead><tr><th>Species</th><th>ν Mn</th><th>Molality</th><th>ν × molality</th></tr></thead><tbody>{c.aqueous.map(a=><tr key={a.id}><td>{a.name}</td><td>{a.coefficient}</td><td>{f(a.molality,'concentration')}</td><td>{f(a.weightedMolality,'concentration')}</td></tr>)}</tbody></table></div><h4>Dissolved oxidation states</h4>{c.oxidationStates.map(a=><p key={a.id}>Mn(+{a.id}): {f(a.weightedMolality,'concentration')} mol/kg-H₂O</p>)}<JsonDetails title="Inactive solid saturation and amounts" value={c.inactiveSolids}/></>}
 {regions&&view!=='sampled'&&<JsonDetails title="Boundary crossing provenance (nearest stored sample neighborhood)" value={regions.boundaries.filter(b=>Math.abs((b.left.pH+b.right.pH)/2-point.pH)<=1&&Math.abs((b.left.Eh+b.right.Eh)/2-point.Eh)<=.25)}/>}<JsonDetails title="Numerical residuals and fixed controls" value={{constraints:raw.input.constraints,residuals:raw.result.residuals,diagnostics:raw.diagnostics}}/><JsonDetails title="Classification, comparison bounds and reason" value={c}/><JsonDetails title="Exact original equilibrium result and attempts" value={raw}/><JsonDetails title="Audited species, oxidation derivations and source provenance" value={snapshot.inventory}/></aside></div></ExpandedPlot></>}
 </section>
}
