import { outputDefinitions, componentOutputTypes } from '../calculations/outputs.js'
import { chemicalLabel } from '../chemistry/format.js'
import { outputGroups as groups } from '../calculations/outputDescriptors.js'
export default function OutputControls({session,components,onView,hasSolid=false,solidName=null,mixed=false,label='F / Z output quantity',hideSelector=false}){
  const plot=session.visualizationState.plot??{},type=plot.type??'log-concentration'
  return <>{!hideSelector&&<label>{label}<select aria-label="Plot output" value={type==='log-solubility'?'log-total-dissolved':type} onChange={e=>onView({type:e.target.value,visibleIds:null,classify:false,colorRange:null,yRange:null})}>{Object.entries(mixed?{Diagrams:['saturated-log-solubility','aqueous-fraction']}:groups).map(([group,ids])=><optgroup key={group} label={group}>{ids.map(id=><option key={id} value={id} disabled={id==='saturated-log-solubility'&&!hasSolid || id==='aqueous-fraction'&&session.calculationDefinition.dimensions===2} title={id==='saturated-log-solubility'?'Requires an included relevant pure solid under the current phase policy; unsaturated samples are unavailable.':undefined}>{outputDefinitions[id].label}</option>)}</optgroup>)}<optgroup label="Diagnostics"><option disabled>Status / failures — see Analysis panel</option></optgroup></select></label>}
    {['fraction','aqueous-fraction',...componentOutputTypes].includes(type)&&!(mixed&&type==='saturated-log-solubility')&&<label>Inventory component<select value={plot.componentId??''} onChange={e=>onView({componentId:e.target.value,visibleIds:null})}><option value="">Choose component</option>{components.filter(c=>!['solvent','electron','proton'].includes(c.role)).map(c=><option key={c.id} value={c.id}>{chemicalLabel(c.name)}</option>)}</select></label>}
    {type==='saturated-log-solubility'&&solidName&&<p>Selected pure solid: <strong>{chemicalLabel(solidName)}</strong></p>}
    {type==='saturated-log-solubility'&&!mixed&&<small>Requires a relevant saturated pure solid. Free component + coefficient-weighted aqueous species; log₁₀ molality. Unsaturated/failed points remain unavailable. Contributor identities appear in output metadata.</small>}
    {type==='aqueous-fraction'&&<small>Distribution within the dissolved component only. Solids are excluded from normalization and remain separately inspectable. Reuse an existing pH result with Return to results.</small>}{type==='fraction'&&<small>Legacy analytical inventory distribution, including solids; this is not the aqueous fraction diagram.</small>}
    {type==='calculated-redox'&&<label>Redox output<select value={plot.redoxQuantity??'pe'} onChange={e=>onView({redoxQuantity:e.target.value})}><option>pe</option><option>Eh</option></select></label>}</>
}
