import {pourbaixCarrierDetails,pourbaixScientificLabel} from '../plots/pourbaixExperience.js'
import {useContext,useMemo} from 'react'
import {ResultSelectionContext} from './ResultSelectionContext.js'
import {pourbaixSample,exportPourbaix} from '../calculations/boundedPourbaix.js'
import {isCurrentUserPourbaix} from '../calculations/userPourbaix.js'
import {pourbaixSvg,pourbaixRepresentatives,pourbaixSampleIndex,pourbaixKeyboardIndex} from '../plots/pourbaixView.js'
import {pourbaixPresentation} from '../plots/pourbaixPresentation.js'
import {chemicalLabel} from '../chemistry/format.js'
import {DiscoveryDetails} from './PourbaixSetup.jsx'
import PlotExport from './PlotExport.jsx'
import './FePourbaix.css'
import './Pourbaix.css'
const number=n=>Number.isFinite(n)?Number(n.toPrecision(10)).toString():'Unavailable'
const download=(text,type,name)=>{const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function PourbaixWorkspace({session}){
 const shared=useContext(ResultSelectionContext),r=session.lastPlot.pourbaix,index=shared.index,current=isCurrentUserPourbaix(session,r)
 const c=current?pourbaixSample(r,index,session.revision):null
 const {view,svg,representatives}=useMemo(()=>{const view=pourbaixPresentation(r);return {view,svg:current?pourbaixSvg(r,index,session.revision,view):'',representatives:pourbaixRepresentatives(r,view)}},[r,index,session.revision,current])
 const {pH:X,Eh:Y}=r.contract,name=r.label
 const sample=e=>{const b=e.currentTarget.getBoundingClientRect();return pourbaixSampleIndex(r.contract,X.min+((e.clientX-b.left)/b.width*900-68)/800*(X.max-X.min),Y.min+(596-(e.clientY-b.top)/b.height*660)/558*(Y.max-Y.min))}
 const status=pourbaixScientificLabel(r.support.scientificStatus),carrierDetails=c?pourbaixCarrierDetails(c):null
 return <section className="fe-workspace pourbaix-workspace" data-diagram="pourbaix"><h2>{name} oxidation-state predominance</h2><p className="pourbaix-status">{status}{!current?' · OLD CONDITIONS':''}</p><p className="fe-contract">Total {name} = {number(r.contract.total)} mol/kg H₂O · 25 °C · 1 bar declared · Ideal<br/>{r.grid.shape.join(' × ')} calculated points · {r.support.claim}</p>
 {!c?<p role="alert">This map belongs to old or unavailable conditions. Recalculate to inspect the current equilibrium.</p>:<>
 <div className="fe-legend" aria-label="Oxidation-state regions">{Object.entries(view.styles).map(([state,s])=><button key={state} disabled={!representatives[state]} onClick={()=>shared.pin(representatives[state].index)}><span style={{background:s.color}}/>{s.label}</button>)}</div>
 <div className="plot-toolbar"><PlotExport><button onClick={()=>download(svg,'image/svg+xml',`${name}-pourbaix.svg`)}>Export SVG</button><button onClick={()=>download(JSON.stringify(exportPourbaix(r,session.revision),null,2),'application/json',`${name}-pourbaix.json`)}>Export numerical JSON</button></PlotExport></div>
 <div className="fe-map" tabIndex={0} role="group" aria-label="Interactive Pourbaix map" aria-describedby="pourbaix-map-help" onPointerMove={e=>{if(e.pointerType!=='touch')shared.preview(sample(e))}} onPointerLeave={()=>shared.preview(null)} onClick={e=>shared.pin(sample(e))} onKeyDown={e=>{const next=pourbaixKeyboardIndex(r.contract,shared.pinned,e.key);if(next!==null){e.preventDefault();shared.pin(next)}}} dangerouslySetInnerHTML={{__html:svg}}/>
 <p className="fe-note">Color shows oxidation state. Select a sample to see its exact aqueous, protonation/hydrolysis or solid carrier below; carrier changes can occur within one color region.</p><p id="pourbaix-map-help" className="fe-note">Click or hover to inspect a calculated point. Arrow keys select adjacent samples; Home/End select the first/last. Sampled boundaries: ΔpH {number(X.step)} · ΔEh {number(Y.step)} V.</p><p className="fe-note">Colors identify oxidation states, not physical compound colors. Hatching shows regions above O₂ and below H₂; these remain calculated fixed-Eh equilibria.</p>
 <section className="fe-inspection" aria-label="Pourbaix point inspection" data-input-id={c.inputId} data-sample-index={index}><h3>{view.styles[c.predominant]?.label??'Tie / transition'} <small>· sample {index}</small></h3><div className="pourbaix-carrier-summary" aria-live="polite"><span className="pourbaix-carrier-badge">{view.styles[c.predominant]?.label??'Tie / transition'}</span>{carrierDetails.dominant.map(p=><div key={p.id}><strong>{chemicalLabel(p.name)}</strong> <span>{p.phase}</span><p>{number(100*p.fraction)}% of total {name} carried by this species</p></div>)}<p>Dissolved: <strong>{number(100*carrierDetails.dissolvedFraction)}% of total {name}</strong></p><small>{status} · Exact selected equilibrium shared with Beaker</small></div><label>Map sample<input type="number" min="0" max={r.points.length-1} aria-label="Pourbaix map sample" value={index} onChange={e=>shared.pin(Number(e.target.value))}/></label><p>pH {number(c.pH)} · Eh {number(c.Eh)} V vs SHE · pe {number(c.pe)}<br/>Total {name}: {number(c.totalInventory)} mol/kg H₂O</p><table><caption>Oxidation-state inventory · denominator is total {name}</caption><tbody>{c.fractions.map(f=><tr key={f.oxidationState}><th scope="row">{view.styles[f.oxidationState].label}</th><td>{number(100*f.fraction)}% of total {name}</td></tr>)}</tbody></table><p>Predominant: {view.styles[c.predominant]?.label??'Tie / transition'} · Majority (&gt;50%): {c.majority?'yes':'no'} · Tie: {c.status==='tie'?'yes':'no'}</p><p><strong>Dominant thermodynamic carrier:</strong> {c.dominantThermodynamicCarriers.map(p=>`${chemicalLabel(p.name)} (${p.phase})`).join(', ')||'No single carrier assigned during a tie'}</p><p>Dissolved {name}: {number(c.dissolvedInventory)} mol/kg H₂O<br/>Accepted solids: {c.acceptedSolids.map(s=>`${chemicalLabel(s.name)}: ${number(s.amount)} mol/kg H₂O`).join('; ')||'none'}<br/>Water context: {c.waterWindow.replaceAll('-',' ')}<br/>Solver: {c.solverStatus} · Unresolved {name} inventory: {number(c.unresolvedInventory)} mol/kg H₂O</p><details className="pourbaix-carriers"><summary>Aqueous / acid-base forms and solid carriers</summary><p>Exact source species identities preserve protonation and hydrolysis forms. Percentages include all oxidation-state allocations of each carrier and use total {name} as denominator.</p><table><caption>Carrier inventory · same selected equilibrium</caption><thead><tr><th>Source species</th><th>Type</th><th>% of total {name}</th></tr></thead><tbody>{carrierDetails.all.filter(p=>p.componentAmount>0).map(p=><tr key={p.id}><th scope="row">{chemicalLabel(p.name)}<small>{p.id}</small></th><td>{p.phase}</td><td>{number(100*p.fraction)}%</td></tr>)}</tbody></table></details><details><summary>Exact fractions, carriers and provenance</summary><pre>{JSON.stringify(c,null,2)}</pre></details></section>
 </>}
 <DiscoveryDetails discovery={r.discovery}/><p className="fe-note">Water references assume unit normalized H₂/O₂ fugacity and a(H₂O)=1, with SHE-based Eh. Gas inventory, kinetics, corrosion rates and coupled multi-element redox are not calculated.</p></section>
}
