import ProblemSummary from './ProblemSummary.jsx'
import EquilibriumConstraints from './EquilibriumConstraints.jsx'
import {useEffect,useRef,useState} from 'react'
import {areaIdentity,prepareArea,runArea,inspectArea,configureEhPhArea} from '../calculations/predominanceArea.js'
import {carrierColors} from '../experimental/carrierPourbaix.js'
import AxisControls from './AxisControls.jsx'
import FixedCondition from './FixedCondition.jsx'
import {editFixedCondition} from '../calculations/setupEditing.js'
import {ResultSelectionContext} from './ResultSelectionContext.js'
import InteractiveBeaker from './InteractiveBeaker.jsx'
import './PredominanceArea.css'
const num=n=>Number.isFinite(n)?Number(n.toPrecision(6)).toString():'unavailable'
const axisLabel=a=>a?`${a.quantity}${a.quantity==='Eh'?' / V vs SHE':a.quantity==='total'?' / '+(a.mode==='LTV'?'log₁₀ ':'')+'mol/kg H₂O':''}`:'Choose coordinate'
export default function PredominanceArea({session,repository,components,onChange,diagramSelector,onPlot}){
 const d=session.calculationDefinition,key=areaIdentity(session),[preparation,setPreparation]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[selected,setSelected]=useState(0),[inspection,setInspection]=useState(null),controller=useRef(null),identity=useRef(key)
 useEffect(()=>{identity.current=key;controller.current?.abort();let active=true;prepareArea(session,repository).then(p=>{if(active)setPreparation({key,value:p})}).catch(e=>{if(active)setPreparation({key,value:{ok:false,reason:e.message}})});return()=>{active=false;controller.current?.abort()}},[key,repository,session])
 const [expanded,setExpanded]=useState(false),resultsHost=useRef(null)
 useEffect(()=>{if(expanded&&result){const frame=requestAnimationFrame(()=>{resultsHost.current?.focus({preventScroll:true});resultsHost.current?.scrollIntoView({block:'start'})});return()=>cancelAnimationFrame(frame)}},[expanded,result])
 const p=preparation?.key===key?preparation.value:null,current=result?.requestIdentity===key?result:null
 useEffect(()=>{let active=true;if(current)inspectArea(current,selected).then(value=>{if(active)setInspection({map:current,index:selected,value})});return()=>{active=false}},[current,selected])
 const detail=inspection?.map===current&&inspection.index===selected?inspection.value:null
 async function calculate(){if(!p?.ok)return;onPlot?.();const abort=new AbortController();controller.current=abort;setBusy(true);setError('');setProgress(0);setSelected(0)
  try{const r=await runArea(p,{signal:abort.signal,isCurrent:()=>identity.current===key,chunkSize:8,onProgress:x=>setProgress(x.completed/x.requested)});if(identity.current===key){if(r.ok){setResult(r);setExpanded(true)}else setError(r.reason)}}catch(e){setError(e.message)}finally{setBusy(false)}
 }
 const axes=d.independentVariables,point=current?.points[selected],regions=current?[...new Map(current.points.flatMap(x=>x.region?[[x.region.id,x.region]]:[])).values()]:[],colors=carrierColors(regions.map(r=>r.id)),shape=current?.grid.shape
 const atEvent=e=>{const b=e.currentTarget.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*800,y=(e.clientY-b.top)/b.height*480;if(x<70||x>775||y<20||y>425)return;setSelected(Math.round((425-y)/405*(shape[1]-1))*shape[0]+Math.round((x-70)/705*(shape[0]-1)))}
 const conventional=axes[0]?.quantity==='pH'&&['Eh','pe'].includes(axes[1]?.quantity)
 const totals=d.componentConditions.filter(c=>components.find(x=>x.id===c.componentId)?.role!=='solvent'&&!c.inferred)
 
 return <section className="area-workspace" aria-label="Predominance area setup">
  {current&&!expanded&&<button onClick={()=>setExpanded(true)}>Reopen retained results</button>}
  <div hidden={expanded&&!!current}><header><strong>Predominance area</strong>{components.some(c=>c.role==='proton')&&components.some(c=>c.role==='electron')&&<button disabled={busy} onClick={()=>onChange(configureEhPhArea(d,components))}>Use Spana-style pH–Eh</button>}{conventional&&<span>pH–Eh / Pourbaix</span>}<button className="calculate" disabled={busy||!p?.ok} onClick={calculate}>Plot diagram</button>{busy&&<><progress value={progress} max="1"/><button onClick={()=>controller.current?.abort()}>Cancel</button></>}</header>
  {!p?<p role="status">Preparing source scope…</p>:!p.ok?<p role="alert">Cannot plot: {p.reason}</p>:null}
  <div className="area-setup-grid">
   <div className="area-y"><AxisControls index={1} definition={d} components={components} onChange={onChange} diagram="predominance"/></div>
   <div className="area-preview" aria-label="Diagram setup preview">{diagramSelector}<span className="area-preview-y">{axisLabel(axes[1])}</span><strong>{p?.interpretation==='oxidation-state'?'Oxidation-state predominance':'Species predominance'}</strong><span>{axisLabel(axes[0])} →</span><label>Region component<select aria-label="Region component" value={d.predominanceArea.componentId} onChange={e=>onChange({...d,predominanceArea:{...d.predominanceArea,componentId:e.target.value}})}>{components.filter(c=>c.role==='basis-choice').map(c=><option key={c.id} value={c.id}>{c.name} · source total</option>)}</select></label><details><summary>Region labels and phases</summary><label>Interpretation<select aria-label="Area interpretation" value={d.predominanceArea.interpretation} onChange={e=>onChange({...d,predominanceArea:{...d.predominanceArea,interpretation:e.target.value}})}><option value="auto">Reviewed oxidation states when available; otherwise carrier</option><option value="carrier">Species / solid predominance</option><option value="oxidation-state">Reviewed oxidation-state allocation required</option></select></label><label>Species phase rule<select aria-label="Species phase rule" value={d.predominanceArea.phasePolicy??'largest-inventory'} onChange={e=>onChange({...d,predominanceArea:{...d.predominanceArea,phasePolicy:e.target.value}})}><option value="solid-first">Spana-style · present solids take priority</option><option value="largest-inventory">Largest component amount across all phases</option><option value="aqueous-only">Dissolved species only</option></select></label></details></div>
   <div className="area-x"><AxisControls index={0} definition={d} components={components} onChange={onChange} diagram="predominance"/><button onClick={()=>onChange({...d,independentVariables:[...axes].reverse()})}>Swap X / Y</button></div>
   <section className="area-fixed"><h3>Fixed composition / activities</h3>{totals.map(c=><FixedCondition compact key={c.componentId} condition={c} component={components.find(x=>x.id===c.componentId)} onChange={next=>onChange(editFixedCondition(d,next))}/>)}</section>
   <section className="area-conditions"><h3>Conditions</h3><p>{d.temperature.value} °C · {d.pressure.value} bar declared · {d.activityModel}</p><p>Ionic strength: {d.ionicStrength.mode==='fixed'?`${d.ionicStrength.value} mol/kg H₂O`:'automatic (not evaluated by ideal model)'}</p><EquilibriumConstraints definition={d} components={components} repository={repository} onChange={onChange}/><p>Phases: {d.enabledPhases.join(', ')}. Gas equilibrium unavailable.</p></section>
  </div>
  <ProblemSummary definition={d} components={components}/>
  {!p?<p role="status">Preparing source scope…</p>:!p.ok?<p role="alert">Unavailable: {p.reason}</p>:<p className="area-status">{p.interpretation==='carrier'?'Species labels use stoichiometry-weighted component amounts. Solid priority follows the selected phase rule; numerical ties remain explicit. These are not oxidation-state regions.':'Authoritative oxidation-state allocation; this general map does not grant independent validation beyond existing reference scopes.'} Sampled cells, no interpolated equilibrium boundaries.</p>}
  </div>
  {error&&<p role="alert">{error}</p>}{result&&!current&&<p role="status">Previous diagram is stale; plot the changed definition.</p>}
  {current&&<div ref={resultsHost} tabIndex={-1} hidden={!expanded} className="area-results"><header><strong>Results · Predominance area</strong><button onClick={()=>setExpanded(false)}>Collapse results</button></header><div className="area-result-split"><div><p role="status">{current.grid.counts.converged} / {current.grid.counts.requested} accepted equilibria · {current.grid.status}</p><svg className="area-map" viewBox="0 0 800 480" role="img" aria-label="Predominance area sampled map" tabIndex="0" onClick={atEvent} onKeyDown={e=>{const delta={ArrowLeft:-1,ArrowRight:1,ArrowDown:-shape[0],ArrowUp:shape[0],Home:-selected,End:current.points.length-1-selected}[e.key];if(delta!==undefined){e.preventDefault();setSelected(Math.max(0,Math.min(current.points.length-1,selected+delta)))}}}>
   <rect x="70" y="20" width="705" height="405" fill="#15222a"/>{current.points.map(cell=>{const w=705/(shape[0]-1),h=405/(shape[1]-1),left=Math.max(70,70+(cell.ix-.5)*w),right=Math.min(775,70+(cell.ix+.5)*w),top=Math.max(20,425-(cell.iy+.5)*h),bottom=Math.min(425,425-(cell.iy-.5)*h);return <rect key={cell.index} x={left} y={top} width={right-left} height={bottom-top} fill={cell.region?colors[cell.region.id]:cell.status==='tie'?'#bbb':'#15222a'}><title>{axisLabel(axes[0])}: {num(cell.x)}; {axisLabel(axes[1])}: {num(cell.y)}; {cell.region?.name??cell.status}</title></rect>})}
   {[0,.25,.5,.75,1].map(t=><g key={t}><text x={70+705*t} y="447" textAnchor="middle">{num(current.grid.coordinates[0][0]+t*(current.grid.coordinates[0].at(-1)-current.grid.coordinates[0][0]))}</text><text x="64" y={429-405*t} textAnchor="end">{num(current.grid.coordinates[1][0]+t*(current.grid.coordinates[1].at(-1)-current.grid.coordinates[1][0]))}</text></g>)}<text x="420" y="472" textAnchor="middle">{axisLabel(axes[0])}</text><text transform="translate(16 225) rotate(-90)" textAnchor="middle">{axisLabel(axes[1])}</text>{point&&<circle cx={70+point.ix/(shape[0]-1)*705} cy={425-point.iy/(shape[1]-1)*405} r="5" fill="none" stroke="white" strokeWidth="2"/>}</svg>
   <div className="area-legend">{regions.map(r=><button key={r.id} onClick={()=>setSelected(current.points.findIndex(p=>p.region?.id===r.id))}><i style={{background:colors[r.id]}}/>{r.name} · {r.phase}</button>)}<span>Dark: unavailable / uncalculated · grey: tie</span></div>
   </div><section aria-label="Area point inspection"><label>Selected sample<input type="number" min="0" max={current.points.length-1} value={selected} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=0&&n<current.points.length)setSelected(n)}}/></label><p>{axisLabel(axes[0])}: {num(point.x)} · {axisLabel(axes[1])}: {num(point.y)} · {point.region?.name??point.status}</p>{!detail?<p>Inspecting exact sampled equilibrium…</p>:!detail.ok?<p>{detail.reason}</p>:<><p>Derived / imposed equilibrium pH: {num(detail.state.pH)} · inspection {num(detail.elapsedMs)} ms. Source inventory and phase amounts below belong to this exact sample.</p><ResultSelectionContext.Provider value={{index:selected,count:current.points.length,pin:setSelected,state:detail.state,theme:'dark'}}><InteractiveBeaker/></ResultSelectionContext.Provider><details><summary>Exact equilibrium and source identity</summary><pre>{JSON.stringify({input:detail.input,result:detail.result},null,2)}</pre></details></>}</section>
   </div><details><summary>Sampling performance</summary><pre>{JSON.stringify(current.timing,null,2)}</pre></details>
  </div>}
  {p?.ok&&<details><summary>Database products / admitted reaction scope</summary><pre>{JSON.stringify({database:p.search.products.map(x=>({id:x.id,name:x.name,phase:x.phase})),admitted:p.system.products,excluded:p.discovery?.excludedCandidates,unsupported:p.discovery?.unsupportedCandidates},null,2)}</pre></details>}
 </section>
}
