import { useState } from 'react'
import { chemicalLabel } from '../chemistry/format.js'
import SpeciesDetails from './SpeciesDetails.jsx'

export default function ReactionReview({ reactionSet, onToggle }) {
  const [query, setQuery] = useState(''), [all, setAll] = useState(false), [phase, setPhase] = useState('all'), [inspect, setInspect] = useState(null), [limit, setLimit] = useState(50)
  const rows = reactionSet.rows.filter(r => (all || r.compatible) && (phase === 'all' || r.species.phase === phase) && `${r.species.name} ${chemicalLabel(r.species.name)} ${r.status}`.toLowerCase().includes(query.toLowerCase()))
  const inspected = reactionSet.rows.find(r => r.species.id === inspect)
  return <section className="species-browser" aria-label="Reaction set review">
    {reactionSet.excludedCount > 0 && <p role="status">Reduced reaction set: {reactionSet.excludedCount} supported aqueous reactions explicitly excluded by you.</p>}
    {!reactionSet.selectedSpecies.length && <p role="status">{reactionSet.excludedCount ? 'User explicitly excluded all supported aqueous products: reduced reaction set.' : reactionSet.rows.some(r => r.compatible && !r.status.includes('identity')) ? 'Compatible records exist, but none are included under the current source and phase policy.' : 'No compatible repository product records. Inspect missing components below.'}</p>}
    <p>Compatible aqueous reactions are included automatically. Excluding a reaction changes equilibrium chemistry and makes existing results stale. Hiding a curve belongs in Shown species.</p>
    <div className="species-search"><label>Search reactions<input type="search" value={query} onChange={e => { setQuery(e.target.value); setLimit(50) }}/></label><label>Reaction phase<select value={phase} onChange={e => setPhase(e.target.value)}>{['all', 'aqueous', 'solid', 'gas', 'liquid'].map(p => <option key={p}>{p}</option>)}</select></label><label className="inline-check"><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)}/>Include records with missing components</label></div>
    <small>{rows.length} records · {reactionSet.selectedSpecies.length} included reactions</small>
    <div className="species-content"><div className="species-table-scroll"><table className="species-table"><thead><tr><th>Species</th><th>Phase / status</th><th>Equilibrium membership</th><th>Source</th></tr></thead><tbody>{rows.slice(0, limit).map(r => <tr key={r.species.id} className={r.included ? 'included' : ''}><td>{chemicalLabel(r.species.name)}{r.acidBase && <small> · proton/solvent equilibrium</small>}</td><td>{r.species.phase} · {r.status}{r.species.provenance.kind === 'user-defined' && <strong> · USER-DEFINED / UNVERIFIED</strong>}</td><td>{r.eligible && <button onClick={() => onToggle(r.species.id)} aria-label={`${r.included ? 'Exclude' : r.species.phase === 'solid' ? 'Include solid' : 'Restore'} ${r.species.name} ${r.included ? 'from' : 'to'} equilibrium`}>{r.included ? 'Exclude from equilibrium' : r.species.phase === 'solid' ? 'Include solid' : 'Restore to equilibrium'}</button>}</td><td><button onClick={() => setInspect(inspect === r.species.id ? null : r.species.id)} aria-label={`Inspect reaction ${r.species.name}`}>Inspect</button></td></tr>)}</tbody></table>{rows.length > limit && <button onClick={() => setLimit(limit + 50)}>Show 50 more reactions</button>}{!rows.length && <p>No matching records.</p>}</div>{inspected && <aside className="species-inspector"><button onClick={() => setInspect(null)}>Close inspector</button><p>{inspected.status}</p><SpeciesDetails species={inspected.species} expanded/></aside>}</div>
    <p>{reactionSet.automaticSolids ? 'Compatible supported solids are considered automatically unless excluded. The bounded solver supports at most 12 candidates.' : 'This configuration preserves explicit solid choices and its existing solver policy.'} Gases and other liquids are unsupported. No missing components, basis substitutions or redox closure are inferred.</p>
  </section>
}
