import WetLabApparatus from './WetLabApparatus.jsx'
import {wetLab3DState} from '../beaker/wetLab3DState.js'
import {ironHydroxideSetup,ironHydroxideScope,ironHydroxideDescription,wetLabExperimentSystem} from '../calculations/ironHydroxideExample.js'
import {nearestWetLabPoint} from '../beaker/wetLab3DState.js'
import './InteractiveBeaker.css'
import WetLabPreparation from './WetLabPreparation.jsx'
import {loadWetLabIons} from '../calculations/wetLabIons.js'
import {preflightWetLab} from '../calculations/wetLabPreflight.js'
import {useEffect,useState,useMemo,useRef} from 'react'
import {createWetLabExperience} from '../calculations/wetLabExperience.js'
import {simplifiedRedoxWetLabSetup,redoxWetLabSetup,analyticalWetLabSetup,defaultWetLabSetup,mixedWetLabSetup,solidWetLabSetup,auditWetLabRecipes,prepareWetLabStocks,wetLabSystemKey} from '../calculations/wetLabSetup.js'
import {wetLabRecipes} from '../calculations/wetLabSolutions.js'
import './WetLab.css'
import WetLabGraph from './WetLabGraph.jsx'
import {createWetLabAnalysis} from '../calculations/wetLabAnalysis.js'

const ml=value=>value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:5})
function PhaseInspection({state}){
 const q=state.equilibrium,inspection=q.inspection
 if(!inspection?.ok)return null
 const present=inspection.solids,absent=inspection.allSolids.filter(s=>s.amount===0)
 return <section className="wet-phases"><strong>Phases</strong><p>{present.length?'Accepted positive solid inventory':'No accepted positive solids'}</p>{present.map(s=>{const product=q.system.products.find(p=>p.id===s.id);return <div key={s.id}><strong>{s.name} · solid</strong><p>{s.amount.toExponential(12)} mol/kg model H₂O · {(s.amount*state.mixture.modelSolventMassKg).toExponential(12)} mol in beaker · log saturation {s.logSaturation.toExponential(6)}</p><small>Source: {s.id}</small><ul>{(q.elementCarriers?Object.entries(q.elementCarriers.find(c=>c.id===s.id)?.elements??{}).filter(([key])=>!['H','O'].includes(key)).map(([key,count])=><li key={key}>{key} bound: {(count*s.amount).toExponential(12)} mol/kg model H₂O</li>):q.system.components.flatMap((c,i)=>c.role==='ordinary'&&product.coefficients[i]>0?[<li key={c.id}>{c.name} bound: {(product.coefficients[i]*s.amount).toExponential(12)} mol/kg model H₂O</li>]:[]))}</ul></div>})}<details><summary>Absent candidates / excluded phases</summary>{absent.map(s=><p key={s.id}>{s.name} · exactly 0 · log saturation {s.logSaturation.toExponential(8)}</p>)}{q.compilerResult?.phaseDiagnostics?.map(s=><p key={s.id}>{s.name}: {s.reason} · log activity {s.logActivity.toExponential(8)}</p>)}{q.compilerResult?.phaseScope?.outsideBoundary?.map(s=><p key={s.id??s.sourceId}>{s.name}: {s.reason}</p>)}</details><small>{inspection.visual.mapping}</small></section>
}
export default function WetLab(props){
 const [experiment,setExperiment]=useState(props.initialExperiment??'acid-base')
 const [previousInitial,setPreviousInitial]=useState(props.initialExperiment)
 if(props.initialExperiment&&props.initialExperiment!==previousInitial){setPreviousInitial(props.initialExperiment);setExperiment(props.initialExperiment)}
 return <><nav className="wet-experiments" aria-label="Wet Lab experiments" role="tablist"><button role="tab" aria-selected={experiment==='acid-base'} aria-controls="wet-acid-base" id="wet-acid-tab" onClick={()=>setExperiment('acid-base')}>Acid/Base Titration</button><button role="tab" aria-selected={experiment==='redox'} aria-controls="wet-redox" id="wet-redox-tab" onClick={()=>setExperiment('redox')}>Redox Titration</button><button role="tab" aria-selected={experiment==='simplified-redox'} aria-controls="wet-simplified-redox" id="wet-simplified-tab" onClick={()=>setExperiment('simplified-redox')}>Simplified Redox</button></nav><div role="tabpanel" id="wet-acid-base" aria-labelledby="wet-acid-tab" hidden={experiment!=='acid-base'}><WetLabExperiment {...props} key={props.emptyVersions?.acid??0} empty={!!props.emptyVersions?.acid} mode="acid-base" active={props.active&&experiment==='acid-base'}/></div><div role="tabpanel" id="wet-redox" aria-labelledby="wet-redox-tab" hidden={experiment!=='redox'}><WetLabExperiment {...props} key={props.emptyVersions?.redox??0} empty={!!props.emptyVersions?.redox} mode="redox" active={props.active&&experiment==='redox'}/></div><div role="tabpanel" id="wet-simplified-redox" aria-labelledby="wet-simplified-tab" hidden={experiment!=='simplified-redox'}><WetLabExperiment {...props} key={props.emptyVersions?.redox??0} empty={!!props.emptyVersions?.redox} mode="simplified-redox" active={props.active&&experiment==='simplified-redox'}/></div></>
}
function WetLabExperiment({repository,chemicalSystem:workspaceSystem,onSystem,mode,active,onBenchState,empty=false}){

 const [ready,setReady]=useState(null),[error,setError]=useState(''),[entry,setEntry]=useState('0'),[busy,setBusy]=useState(false)
 const [delivery,setDelivery]=useState(null)
 const [workspaceView,setWorkspaceView]=useState('titration')
 const [viewType,setViewType]=useState('titration'),[componentId,setComponentId]=useState(''),[focus,setFocus]=useState(null)
 const [setup,setSetup]=useState(()=>{const initial=structuredClone(mode==='simplified-redox'?simplifiedRedoxWetLabSetup:mode==='redox'?redoxWetLabSetup:analyticalWetLabSetup);if(empty)for(const stock of ['sample','titrant'])initial[stock]={...initial[stock],volumeMl:0,contributions:[]};return initial;}),[revision,setRevision]=useState(1),[audit,setAudit]=useState(null)
 const chemicalSystem=useMemo(()=>wetLabExperimentSystem(repository,workspaceSystem,setup),[repository,workspaceSystem,setup])
 const [catalog,setCatalog]=useState(null),[preflight,setPreflight]=useState(null)
 const resultsRef=useRef(null),focusResults=useRef(false)
 const epoch=useRef(0),engineRef=useRef(null),key=wetLabSystemKey(chemicalSystem)
 const binding=useMemo(()=>({repository,key}),[repository,key])
 useEffect(()=>{let current=true;const counter=epoch;auditWetLabRecipes(repository,JSON.parse(key)).then(value=>{if(current)setAudit({binding,value})}).catch(e=>{if(current)setError(e.message)});return()=>{current=false;counter.current++;engineRef.current?.dispose();setBusy(false)}},[repository,key,binding])
 useEffect(()=>{let current=true;loadWetLabIons(repository).then(value=>{if(current)setCatalog({repository,value})}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[repository])
 const ions=catalog?.repository===repository?catalog.value:null
 const selectedCatalog=useMemo(()=>ions?{...ions,systemBound:true,candidates:ions.candidates.filter(c=>Object.keys(c.coefficients??{}).every(id=>chemicalSystem.selectedComponents.includes(id)))}:null,[ions,chemicalSystem])
 useEffect(()=>{let current=true;const timer=setTimeout(()=>{if(ions)preflightWetLab(repository,setup,JSON.parse(key),revision,ions).then(value=>{if(current)setPreflight({value,setup,revision,binding})})},250);return()=>{current=false;clearTimeout(timer)}},[repository,setup,key,revision,ions,binding])
 const flight=preflight?.setup===setup&&preflight?.revision===revision&&preflight?.binding===binding?preflight.value:null
 const availability=audit?.binding===binding?audit.value:null
 const recipes=availability?.recipes??Object.values(wetLabRecipes).map(p=>({id:p.id,label:p.label??p.id,available:false}))
 const preview=useMemo(()=>{try{return {stocks:prepareWetLabStocks(setup,revision,ions)}}catch(e){return {error:e.message}}},[setup,revision,ions])
 const data=ready?.binding===binding&&ready?.revision===revision?ready:null
 useEffect(()=>{if(data&&focusResults.current){focusResults.current=false;resultsRef.current?.focus({preventScroll:true});resultsRef.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}},[data])
 function edit(part,field,value){epoch.current++;engineRef.current?.dispose();setBusy(false);setSetup(s=>({...s,[part]:field==='definition'?value:{...s[part],[field]:value}}));setRevision(r=>r+1);setError('')}
 function example(configuration){epoch.current++;engineRef.current?.dispose();setBusy(false);setSetup(structuredClone(configuration));setRevision(r=>r+1);setError('')}
 async function prepare(){const token=++epoch.current;engineRef.current?.dispose();setBusy(true);setReady(null);setError('');try{const engine=await createWetLabExperience(repository,{chemicalSystem,setup,revision,isCurrent:()=>token===epoch.current});if(token!==epoch.current){engine.dispose();return}setWorkspaceView('titration');setViewType(engine.snapshot().scope.boundary==='closed-physical'?'redox-titration':'titration');setFocus(null);engineRef.current=engine;focusResults.current=true;setReady({engine,analysis:createWetLabAnalysis(engine),snapshot:engine.snapshot(),binding,revision});setEntry('0')}catch(e){if(token===epoch.current)setError(e.message)}finally{if(token===epoch.current)setBusy(false)}}
 function apply(snapshot){setReady({...data,snapshot});setEntry(String(snapshot.selected.titrantVolumeAddedMl));setError('')}
 async function setVolume(value){if(busy||!data)return false;setBusy(true);try{const from=data.snapshot.selected.titrantVolumeAddedMl;const snapshot=await data.engine.setVolume(value);apply(snapshot);const to=snapshot.selected.titrantVolumeAddedMl;if(to>from&&snapshot.selected.status==='accepted-v0')setDelivery({id:performance.now(),from,to,stateId:snapshot.selected.id});return true}catch(e){if(e.code!=='stale-titration')setError(e.message);return false}finally{setBusy(false)}}
 function select(point){try{apply(data.engine.select(point))}catch(e){setError(e.message)}}
 const {selected:committed,displayed:state,preview:previewState,points,capacityMl,sampling}=data?.snapshot??{},result=state?.equilibrium.result
 useEffect(()=>{if(active&&onBenchState)onBenchState(mode,{...wetLab3DState(committed,capacityMl??100,!committed,mode),solidColorMode:'phases',solidMagnification:10,curve:(points??[]).filter(p=>p.state?.status==='accepted-v0').map(p=>({x:p.state.titrantVolumeAddedMl,y:mode==='acid-base'?p.state.pH:p.state.equilibrium?.derived?.Eh})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))})},[active,onBenchState,mode,committed,capacityMl,points])
 const availableComponents=data?.analysis.view('titration').components??[]
 const activeComponent=availableComponents.some(c=>c.id===componentId)?componentId:availableComponents[0]?.id
 const graph=data?.analysis.view(viewType,activeComponent)
 function navigate(key){const i=points.findIndex(p=>p.state===committed);select(points[key==='Home'?0:key==='End'?points.length-1:Math.max(0,Math.min(points.length-1,i+(key==='ArrowLeft'?-1:1)))])}
 function changeView(view){leave();setWorkspaceView(view);setFocus(null);if(view==='titration')setViewType(data?.snapshot.scope.boundary==='closed-physical'?'redox-titration':'titration');if(view==='species')setViewType('log-concentration');if(view==='fractions')setViewType('total-fraction')}
 function hover(point){if(data.snapshot.preview===point.state)return;setReady({...data,snapshot:data.engine.preview(point)})}
 function leave(){if(data?.snapshot.preview)setReady({...data,snapshot:data.engine.clearPreview()})}
 return <main className="wet-lab" aria-label="Wet Lab">
  <details className="wet-mode-notes"><summary>Preparation model and chemistry settings</summary>
  {mode==='simplified-redox'&&<p role="note"><strong>Fictitious inert counterions:</strong> countercharge is supplied automatically. No chloride or nitrate is added. Ideal activities only; this model omits counterion complexation and redox chemistry. Enter acid as H⁺; pH and Eh are calculated after mixing.</p>}
  {setup.experimentScope===ironHydroxideScope&&<p role="note" className="notice"><strong>Fresh iron hydroxide experiment.</strong> {ironHydroxideDescription} This scope applies only to this experiment; System is unchanged. <button onClick={()=>example(analyticalWetLabSetup)}>Return to ordinary setup</button></p>}
  <p>Acid/base and redox titrations share this apparatus. Physical redox stocks calculate pH and Eh from their supplied ions and counterions; no electron selection is needed. <button onClick={onSystem}>Edit chemistry in System</button></p>
  {availability&&!availability.available.length&&<p role="status">No validated physical reagent recipes are available for the current System.</p>}
  </details>
  <div className="wet-experiment-layout"><section className="wet-bench" aria-label="Titration preparation and apparatus" data-state-id={state?.id}>

   <div className="wet-apparatus-editor"><div className="wet-apparatus-drawing">   <header className="wet-setup-header">
    <div><h3>Titration setup</h3><span className="wet-setup-status">{busy?'Preparing…':data?'Prepared':!flight?'Checking…':flight.status==='UNAVAILABLE'?'Unavailable':'Ready · conditional'}</span></div>
    <button className="wet-prepare-primary" aria-describedby={'wet-prepare-status-'+mode} disabled={busy||!flight||flight.status==='UNAVAILABLE'} onClick={prepare}>{busy?'Preparing…':'Prepare experiment'}</button>
    <p id={'wet-prepare-status-'+mode} role="status" aria-label="Preparation preflight">{error||preview.error||(flight?.status==='UNAVAILABLE'?flight.reason:!flight?'Checking preparation…':flight.scope?.boundary==='analytical-acid-base'?'Analytical acid/base · countercharge unspecified. Each dose requires accepted equilibrium.':'Structural preflight passed. Each dose still requires an accepted equilibrium.')}</p>
   </header>
<WetLabApparatus delivery={delivery} experiment={data?.engine} canDispense={!!data&&!busy&&!previewState&&committed?.titrantRemainingMl>0} onDispense={amount=>setVolume(Math.min(capacityMl,committed.titrantVolumeAddedMl+amount))} mode={mode} active={active} preview={!state} onNavigate={data?navigate:undefined} state={state??{titrantVolumeAddedMl:0,pH:null,titrantRemainingMl:Math.max(0,Number(setup.titrant.volumeMl)||0),totalVolumeMl:Math.max(0,Number(setup.sample.volumeMl)||0),initialAnalyte:{volumeMl:Math.max(0,Number(setup.sample.volumeMl)||0)},equilibrium:{}}} capacity={capacityMl??Math.max(1,Number(setup.titrant.volumeMl)||1)}/></div>
   <div className="wet-titrant-editor"><WetLabPreparation catalog={ions} selectionCatalog={selectedCatalog} name="Burette" value={setup.titrant} stock={data?.snapshot.stocks.titrant??flight?.stocks?.titrant??preview.stocks?.titrant} recipes={recipes} onChange={(field,value)=>edit('titrant',field,value)}/></div><div className="wet-sample-editor"><WetLabPreparation catalog={ions} selectionCatalog={selectedCatalog} name="Sample" value={setup.sample} stock={data?.snapshot.stocks.sample??flight?.stocks?.sample??preview.stocks?.sample} recipes={recipes} onChange={(field,value)=>edit('sample',field,value)}/></div></div>
  <details className="wet-presets"><summary>Examples / presets</summary><div className="wet-increments">{mode==='simplified-redox'?<button disabled={!ions} onClick={()=>example(simplifiedRedoxWetLabSetup)}>Dichromate + Fe(II) · inert counterions</button>:mode==='redox'?<button disabled={!ions} onClick={()=>example(redoxWetLabSetup)}>Redox · Fe(II) with Ce(IV)</button>:<><button onClick={()=>example(analyticalWetLabSetup)}>Strong acid/base · analytical H⁺ / OH⁻</button><button onClick={()=>example(mixedWetLabSetup)}>Mixed solution example</button><button onClick={()=>example(solidWetLabSetup)}>Ideal-model precipitation example</button><button disabled={!ions} onClick={()=>example(ironHydroxideSetup)}>Fe(II) + Fe(III) hydroxides · restricted phases</button><button onClick={()=>example(defaultWetLabSetup)}>Validated HCl/NaOH example</button></>}</div><small>Presets fill the setup; they do not prepare an experiment or change System.</small></details>
  <details className="wet-details"><summary>Advanced chemistry scope</summary><p>{flight?.status} · {flight?.reason}</p>{flight?.discovery&&<details><summary>Discovered system requirements</summary><pre>{JSON.stringify(flight.discovery,null,2)}</pre></details>}{recipes.map(r=><p key={r.id}><strong>{r.label}</strong> · {r.available?'Available':r.reasons?.join(' ')??'Checking source identities…'}</p>)}<p>Reviewed recipes supply their intrinsic ions. Required chemistry is resolved for this experiment without changing System inventories; explicit exclusions are respected.</p>{data&&<><p>{data.snapshot.scope.status} · {data.snapshot.scope.reason}</p><pre>{JSON.stringify(data.snapshot.scope,null,2)}</pre></>}</details>
  {ready&&!data&&<p className="notice" role="status">Experiment stale: setup or System changed. Prepare experiment again before dispensing or selecting a sample.</p>}


  </section><section className={`wet-results${data?' wet-results-ready':''}`} aria-label="Titration results" ref={resultsRef} tabIndex={-1}>
  <div className="wet-heading"><div><span className="wet-eyebrow">WET LAB</span><h2>{mode==='simplified-redox'?'Simplified Redox':mode==='redox'?'Redox Titration':'Acid/Base Titration'}</h2></div><span className="badge">25 °C · ideal · additive volumes</span></div>
  {!data&&<div className="wet-results-empty" role="status"><h3>Titration curve</h3><p>Choose the burette and sample solutions beside the apparatus, then prepare the experiment to calculate the curve.</p></div>}
  {data&&<>
  <p className="wet-preview" role="status" data-committed-id={committed.id}>{previewState?`PREVIEW · ${ml(state.titrantVolumeAddedMl)} mL · Selected: ${ml(committed.titrantVolumeAddedMl)} mL. Click to select; leave graph to restore.`:`Selected · ${ml(committed.titrantVolumeAddedMl)} mL`}</p><section className="wet-work"><div className="wet-readout" aria-live="polite" data-state-id={state.id}>
   <div><span>{state.titrant.reagent} added</span><strong>{ml(state.titrantVolumeAddedMl)} <small>mL</small></strong></div><div><span>Burette remaining</span><strong>{ml(state.titrantRemainingMl)} <small>mL</small></strong></div><div><span>Beaker volume</span><strong>{ml(state.totalVolumeMl)} <small>mL</small></strong></div><div className="wet-ph"><span>Calculated pH</span><strong>{state.pH===null?'Unavailable':state.pH.toFixed(5)}</strong></div>
  {state.equilibrium.derived&&<div><span>Derived Eh / V vs SHE</span><strong>{state.equilibrium.derived.Eh.toFixed(5)}</strong></div>}</div><div className="wet-controls"><div className="wet-volume-scrubber"><label>Added volume · rewind / advance<input aria-label="Added volume timeline" type="range" min="0" max={capacityMl} step="any" disabled={busy} value={committed.titrantVolumeAddedMl} onInput={e=>{const p=nearestWetLabPoint(points,Number(e.target.value));if(p)select(p)}}/><small>Snaps to calculated doses. Enter an exact volume below to calculate another point.</small></label><output>{ml(committed.titrantVolumeAddedMl)} mL</output></div><div className="wet-increments"><button onClick={()=>apply(data.engine.reset())}>Reset to 0 mL</button></div>
   <form onSubmit={e=>{e.preventDefault();setVolume(entry)}}><label>Total {state.titrant.reagent} added <span><input aria-label="Total titrant added" type="number" min="0" max={capacityMl} step="any" value={entry} onChange={e=>setEntry(e.target.value)}/> mL</span></label><button disabled={busy}>Apply volume</button>{sampling.nearEquivalenceMl!==null&&<button type="button" onClick={()=>setVolume(sampling.nearEquivalenceMl)}>Near expected equivalence</button>}</form>
  </div>{error&&<p role="alert">{error}</p>}{state.status!=='accepted-v0'&&<p role="alert">Equilibrium unavailable: {state.diagnostics.map(d=>d.message).join(' ')}</p>}
  <nav className="wet-result-views" aria-label="Experiment result views">{[['titration','Titration curve'],['species','Species'],['fractions','Fractions'],['solids','Solids']].map(([view,label])=><button key={view} aria-pressed={workspaceView===view} onClick={()=>changeView(view)}>{label}</button>)}</nav>
  {workspaceView==='solids'&&<section className="wet-solid-view" data-state-id={state.id}>{state.equilibrium.inspection?.ok?<PhaseInspection state={state}/>:<p>No accepted equilibrium at this dose.</p>}</section>}
  <section className="wet-chart" data-state-id={state.id}>{workspaceView!=='solids'&&<><label>Graph<select aria-label="Wet Lab graph" value={viewType} onChange={e=>{leave();setViewType(e.target.value);setWorkspaceView(['titration','redox-titration'].includes(e.target.value)?'titration':e.target.value.includes('fraction')?'fractions':'species');setFocus(null)}}><option value="titration">pH titration curve</option><option value="redox-titration">Redox titration · Eh vs volume</option><option value="log-concentration">Log concentrations</option><option value="log-activity">Log activities</option><option value="total-fraction">Total fractions</option><option value="aqueous-fraction">Aqueous speciation</option></select></label>{["total-fraction","aqueous-fraction"].includes(viewType)&&<label>Analytical component<select aria-label="Wet Lab analytical component" value={activeComponent??""} onChange={e=>{leave();setComponentId(e.target.value);setFocus(null)}}>{availableComponents.map(c=><option key={c.id} value={c.id}>{c.id==='component:CH3COO-'?'Acetate':c.id==='component:B(OH)3'?'Boron':c.name}</option>)}</select><small>Signed proton equivalents are excluded. Zero/absent component inventory remains a gap.</small></label>}<WetLabGraph view={graph} state={state} committed={committed} capacity={capacityMl} focus={focus} onFocus={setFocus} onSelect={select} onPreview={hover} onLeave={leave}/></>}<div className="wet-sample-navigation"><button aria-label="Previous calculated dose" disabled={points[0].state===committed} onClick={()=>navigate('ArrowLeft')}>←</button><button aria-label="Next calculated dose" disabled={points.at(-1).state===committed} onClick={()=>navigate('ArrowRight')}>→</button></div><label>Calculated sample <select aria-label="Calculated sample" value={points.findIndex(p=>p.state===committed)} onChange={e=>select(points[Number(e.target.value)])}>{points.map((p,i)=><option key={p.x} value={i}>{ml(p.x)} mL · {p.y===null?'unavailable':`pH ${p.y.toFixed(5)}`}</option>)}</select></label><small>Click a sample or use ← / → on the curve. Selection uses a calculated state; lines only connect samples.</small></section>
  </section>
  <details className="wet-details"><summary>Experiment scope and sampling</summary><p>Equilibrium evaluations: {data.snapshot.equilibriumSolveCount} · stock preparation {data.snapshot.timings.stockPreparationMs.toFixed(1)} ms · initial series {data.snapshot.timings.seriesMs.toFixed(1)} ms. Cached views and accepted-dose selection do not solve.</p><p className="wet-prepared-summary">Revision {revision} · sample {ml(state.initialAnalyte.volumeMl)} mL: {state.initialAnalyte.contributions.map(r=>`${r.reagent} ${r.concentrationMolPerL*1000} mM`).join(' + ')} · {data.snapshot.scope.status}</p>
  {sampling.equivalenceMl!==null&&<p className="hint">Inventory-derived sampling estimate: {ml(sampling.equivalenceMl)} mL{sampling.equivalenceMl>capacityMl?' · beyond loaded burette inventory; no equivalence shortcut is available.':'. This is a navigation aid, not an imposed pH.'}</p>}
</details>
  <details className="wet-details" data-state-id={state.id}><summary>Selected equilibrium inspection</summary><p>Exact accepted pH: {state.pH??'unavailable'} · proton-equivalent inventory: {state.analyticalMoles.protonEquivalent.toExponential(10)} mol</p>{state.status==='accepted-v0'&&<table><thead><tr><th>Species</th><th>mol/kg model H₂O</th></tr></thead><tbody>{[...state.equilibrium.system.components.filter(c=>c.role!=='water').map(c=>[c.name,c.id]),...state.equilibrium.system.products.filter(p=>p.phase==='aqueous').map(p=>[p.name,p.id])].map(([label,id])=>{const i=result.speciesIds.indexOf(id);return <tr key={id}><td>{label}</td><td>{i<0?'0 (zero supplied inventory)':result.concentrations[i].toExponential(10)}</td></tr>})}</tbody></table>}<PhaseInspection state={state}/>{state.equilibrium.inertCountercharge&&<p>Fictitious inert countercharge: {state.equilibrium.inertCountercharge.background.toExponential(6)} eq/kg · total charge residual {state.equilibrium.inertCountercharge.residual.toExponential(3)} eq/kg · {state.equilibrium.inertCountercharge.ok?'passed':'failed'}. No chemical counterion identity is implied.</p>}<p>Accepted input: <code>{state.equilibrium.input?.id}</code></p><p>{state.scientificStatus}</p><p>{state.equilibrium.derived?`Derived Eh: ${state.equilibrium.derived.Eh.toPrecision(10)} V vs SHE · pe: ${state.equilibrium.derived.pe.toPrecision(10)} (closed redox)`:'Eh / pe: not determined in this non-redox scope.'}</p><details><summary>Preparation additions / counterions</summary><ul>{state.mixture.contributions.map(r=><li key={r.id}>{r.reagent}: {r.moles.toExponential(6)} mol supplied · intrinsic components {JSON.stringify(r.intrinsicComponents)} · automatic additions: {r.automaticAdditions.length?JSON.stringify(r.automaticAdditions):'none beyond the selected recipe'}</li>)}</ul></details><details><summary>Preparation / mixing provenance</summary><pre>{JSON.stringify(state.mixture,null,2)}</pre></details></details>
  </>}
  </section></div>
  <details className="wet-details"><summary>Model assumptions</summary><p>dilute-ideal-aqueous-volume-v0 · additive delivered solution volumes · 1 model kg H₂O per litre solution numerical coordinate · ideal activities · 25 °C · unit water activity.</p><p>This numerical coordinate is not measured solvent mass or exact density. Volumetric contraction and nonideal activities are not modeled; this is not an experimental-grade accuracy claim for entered concentrations. Cyan identifies liquid, not compound or indicator colour. Phase/gas requirements are audited under the selected compiler scope. Unsupported requirements remain unavailable. Each delivered volume is equilibrated independently from original stocks: no nucleation, ageing, hysteresis or persistence of a previous precipitate is modeled. Sediment height is schematic, not physical solid volume. The concentrated precipitation example is an ideal-model integration control, not a nonideal experimental prediction. No finite headspace or gas-loss model is included; this does not imply zero volatilization.</p></details>
 </main>
}
